[2024-10-01 00:56:38,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 00:56:38,694] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 02:23:21,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 02:23:21,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:09:21,419] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:09:21,766] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:40:21,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:40:21,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:52:37,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:52:37,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:13:44,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:13:44,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:33:58,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:33:58,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:49:00,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:49:00,572] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:11:21,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:11:22,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:30:47,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:30:48,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:48:14,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:48:14,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:15:48,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:15:49,288] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:44:32,490] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:44:32,849] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:53:13,636] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:53:14,018] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:11:31,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:11:32,148] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:26:50,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:26:50,472] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:35:36,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:35:36,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:47:34,023] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:47:34,378] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:15:00,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:15:00,782] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:36:32,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:36:33,189] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:51:33,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:51:34,098] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:12:07,789] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:12:08,147] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:30:09,328] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:30:09,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:40:52,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:40:52,750] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:48:11,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:48:11,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:11:46,481] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:11:46,850] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:34:37,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:34:37,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:48:35,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:48:35,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:09:17,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:09:17,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:25:06,520] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:25:06,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:33:45,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:33:45,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:47:59,182] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:47:59,529] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 12:20:52,353] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 12:20:52,675] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 12:58:22,201] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 12:58:22,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:25:06,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:25:06,476] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:40:09,077] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:40:09,444] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:47:41,552] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:47:41,890] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:10:30,703] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:10:31,119] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:30:59,418] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:30:59,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:47:53,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:47:53,723] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:11:12,216] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:11:12,622] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:29:29,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:29:30,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:40:09,583] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:40:09,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:48:06,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:48:06,649] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:13:39,933] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:13:40,300] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:37:03,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:37:04,056] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:51:28,231] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:51:28,652] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:09:56,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:09:56,718] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:28:53,401] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:28:53,671] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:38:46,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:38:46,786] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:47:41,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:47:41,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:14:21,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:14:22,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:37:13,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:37:14,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:50:09,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:50:09,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:09:03,986] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:09:04,197] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:21:58,258] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:21:58,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:34:03,238] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:34:03,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:47:51,420] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:47:51,851] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:11:44,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:11:44,619] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:28:46,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:28:47,141] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:38:55,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:38:55,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:48:27,450] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:48:27,808] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:11:06,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:11:06,607] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:26:56,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:26:56,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:36:10,715] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:36:10,959] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:47:44,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:47:45,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:10:40,559] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:10:40,927] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:30:09,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:30:09,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:41:06,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:41:07,082] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:48:18,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:48:18,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:10:23,276] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:10:23,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:25:47,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:25:47,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:34:22,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:34:22,824] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:48:00,143] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:48:00,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 00:51:37,131] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 00:51:37,465] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 02:12:51,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 02:12:51,734] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 02:56:29,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 02:56:30,355] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:17:29,948] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:17:30,349] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:40:55,654] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:40:56,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:48:55,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:48:56,339] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:13:18,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:13:18,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:33:06,189] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:33:06,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:48:30,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:48:31,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:11:22,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:11:22,423] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:30:39,669] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:30:40,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:47:27,680] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:47:28,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:15:26,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:15:27,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:38:39,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:38:39,867] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:51:04,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:51:04,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:10:30,547] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:10:30,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:25:03,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:25:03,836] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:34:00,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:34:01,327] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:47:41,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:47:41,332] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:14:20,396] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:14:20,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:35:06,362] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:35:06,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:50:41,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:50:42,254] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:11:34,532] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:11:34,944] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:28:46,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:28:47,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:39:07,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:39:07,572] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:47:36,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:47:36,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:11:29,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:11:29,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:32:41,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:32:42,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:47:47,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:47:48,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:09:17,988] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:09:18,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:23:07,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:23:07,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:33:41,959] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:33:42,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:47:44,188] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:47:44,514] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 12:20:36,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 12:20:36,524] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 12:57:04,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 12:57:05,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:21:36,853] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:21:37,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:38:35,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:38:35,588] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:47:38,321] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:47:38,498] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:10:25,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:10:25,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:28:55,654] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:28:56,009] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:39:41,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:39:42,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:47:44,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:47:44,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:11:28,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:11:28,910] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:29:44,499] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:29:44,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:40:48,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:40:48,970] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:47:55,235] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:47:55,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:13:23,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:13:23,708] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:35:39,860] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:35:40,146] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:50:55,928] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:50:56,267] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:09:30,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:09:30,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:27:33,949] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:27:34,330] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:37:01,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:37:02,374] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:47:35,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:47:35,438] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:15:15,852] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:15:16,157] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:38:13,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:38:13,514] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:50:26,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:50:27,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:08:58,270] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:08:58,643] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:22:24,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:22:24,229] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:34:04,352] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:34:04,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:47:37,477] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:47:37,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:12:35,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:12:35,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:31:07,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:31:07,724] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:47:52,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:47:52,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:12:05,774] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:12:06,217] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:28:19,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:28:19,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:38:42,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:38:42,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:47:50,251] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:47:50,627] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:11:32,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:11:32,864] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:31:20,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:31:20,509] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:47:41,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:47:41,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:10:38,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:10:39,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:26:07,591] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:26:07,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:35:26,845] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:35:27,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:48:00,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:48:00,964] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
