[2024-10-01 00:56:38,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 00:56:38,694] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 02:23:21,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 02:23:21,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:09:21,419] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:09:21,766] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:40:21,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:40:21,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:52:37,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:52:37,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:13:44,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:13:44,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:33:58,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:33:58,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:49:00,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:49:00,572] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:11:21,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:11:22,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:30:47,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:30:48,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:48:14,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:48:14,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:15:48,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:15:49,288] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:44:32,490] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:44:32,849] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
