[2024-10-01 00:56:38,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 00:56:38,694] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 02:23:21,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 02:23:21,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:09:21,419] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:09:21,766] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:40:21,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:40:21,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 03:52:37,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 03:52:37,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:13:44,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:13:44,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:33:58,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:33:58,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 04:49:00,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 04:49:00,572] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:11:21,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:11:22,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:30:47,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:30:48,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 05:48:14,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 05:48:14,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:15:48,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:15:49,288] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:44:32,490] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:44:32,849] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 06:53:13,636] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 06:53:14,018] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:11:31,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:11:32,148] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:26:50,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:26:50,472] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:35:36,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:35:36,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 07:47:34,023] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 07:47:34,378] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:15:00,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:15:00,782] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:36:32,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:36:33,189] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 08:51:33,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 08:51:34,098] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:12:07,789] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:12:08,147] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:30:09,328] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:30:09,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:40:52,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:40:52,750] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 09:48:11,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 09:48:11,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:11:46,481] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:11:46,850] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:34:37,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:34:37,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 10:48:35,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 10:48:35,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:09:17,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:09:17,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:25:06,520] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:25:06,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:33:45,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:33:45,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 11:47:59,182] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 11:47:59,529] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 12:20:52,353] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 12:20:52,675] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 12:58:22,201] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 12:58:22,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:25:06,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:25:06,476] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:40:09,077] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:40:09,444] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 13:47:41,552] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 13:47:41,890] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:10:30,703] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:10:31,119] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:30:59,418] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:30:59,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 14:47:53,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 14:47:53,723] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:11:12,216] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:11:12,622] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:29:29,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:29:30,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:40:09,583] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:40:09,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 15:48:06,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 15:48:06,649] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:13:39,933] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:13:40,300] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:37:03,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:37:04,056] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 16:51:28,231] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 16:51:28,652] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:09:56,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:09:56,718] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:28:53,401] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:28:53,671] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:38:46,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:38:46,786] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 17:47:41,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 17:47:41,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:14:21,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:14:22,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:37:13,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:37:14,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 18:50:09,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 18:50:09,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:09:03,986] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:09:04,197] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:21:58,258] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:21:58,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:34:03,238] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:34:03,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 19:47:51,420] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 19:47:51,851] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:11:44,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:11:44,619] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:28:46,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:28:47,141] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:38:55,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:38:55,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 20:48:27,450] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 20:48:27,808] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:11:06,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:11:06,607] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:26:56,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:26:56,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:36:10,715] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:36:10,959] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 21:47:44,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 21:47:45,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:10:40,559] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:10:40,927] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:30:09,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:30:09,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:41:06,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:41:07,082] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 22:48:18,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 22:48:18,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:10:23,276] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:10:23,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:25:47,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:25:47,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:34:22,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:34:22,824] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-01 23:48:00,143] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-01 23:48:00,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 00:51:37,131] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 00:51:37,465] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 02:12:51,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 02:12:51,734] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 02:56:29,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 02:56:30,355] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:17:29,948] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:17:30,349] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:40:55,654] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:40:56,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 03:48:55,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 03:48:56,339] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:13:18,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:13:18,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:33:06,189] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:33:06,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 04:48:30,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 04:48:31,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:11:22,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:11:22,423] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:30:39,669] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:30:40,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 05:47:27,680] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 05:47:28,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:15:26,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:15:27,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:38:39,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:38:39,867] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 06:51:04,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 06:51:04,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:10:30,547] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:10:30,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:25:03,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:25:03,836] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:34:00,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:34:01,327] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 07:47:41,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 07:47:41,332] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:14:20,396] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:14:20,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:35:06,362] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:35:06,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 08:50:41,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 08:50:42,254] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:11:34,532] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:11:34,944] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:28:46,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:28:47,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:39:07,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:39:07,572] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 09:47:36,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 09:47:36,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:11:29,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:11:29,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:32:41,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:32:42,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 10:47:47,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 10:47:48,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:09:17,988] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:09:18,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:23:07,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:23:07,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:33:41,959] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:33:42,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 11:47:44,188] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 11:47:44,514] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 12:20:36,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 12:20:36,524] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 12:57:04,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 12:57:05,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:21:36,853] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:21:37,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:38:35,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:38:35,588] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 13:47:38,321] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 13:47:38,498] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:10:25,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:10:25,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:28:55,654] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:28:56,009] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:39:41,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:39:42,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 14:47:44,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 14:47:44,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:11:28,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:11:28,910] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:29:44,499] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:29:44,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:40:48,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:40:48,970] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 15:47:55,235] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 15:47:55,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:13:23,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:13:23,708] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:35:39,860] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:35:40,146] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 16:50:55,928] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 16:50:56,267] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:09:30,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:09:30,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:27:33,949] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:27:34,330] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:37:01,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:37:02,374] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 17:47:35,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 17:47:35,438] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:15:15,852] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:15:16,157] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:38:13,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:38:13,514] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 18:50:26,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 18:50:27,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:08:58,270] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:08:58,643] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:22:24,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:22:24,229] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:34:04,352] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:34:04,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 19:47:37,477] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 19:47:37,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:12:35,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:12:35,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:31:07,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:31:07,724] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 20:47:52,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 20:47:52,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:12:05,774] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:12:06,217] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:28:19,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:28:19,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:38:42,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:38:42,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 21:47:50,251] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 21:47:50,627] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:11:32,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:11:32,864] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:31:20,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:31:20,509] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 22:47:41,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 22:47:41,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:10:38,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:10:39,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:26:07,591] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:26:07,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:35:26,845] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:35:27,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-02 23:48:00,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-02 23:48:00,964] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 00:51:33,045] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 00:51:33,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 02:13:31,744] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 02:13:32,142] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 02:57:22,775] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 02:57:23,154] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 03:20:04,550] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 03:20:04,871] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 03:40:38,527] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 03:40:38,948] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 03:48:24,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 03:48:24,286] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 04:14:01,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 04:14:02,339] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 04:34:48,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 04:34:48,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 04:49:43,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 04:49:43,473] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 05:10:58,824] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 05:10:59,129] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 05:30:49,038] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 05:30:49,426] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 05:47:47,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 05:47:47,880] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 06:15:27,943] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 06:15:28,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 06:43:01,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 06:43:01,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 06:51:28,854] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 06:51:29,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 07:10:58,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 07:10:58,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 07:26:15,593] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 07:26:15,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 07:35:00,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 07:35:00,796] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 07:47:52,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 07:47:52,452] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 08:14:34,741] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 08:14:35,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 08:34:31,156] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 08:34:31,361] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 08:50:12,022] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 08:50:12,291] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 09:11:34,202] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 09:11:34,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 09:29:09,233] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 09:29:09,505] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 09:39:07,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 09:39:08,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 09:47:43,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 09:47:43,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 10:11:36,044] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 10:11:36,445] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 10:33:12,390] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 10:33:12,736] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 10:47:44,460] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 10:47:44,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 11:09:12,777] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 11:09:13,120] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 11:23:10,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 11:23:10,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 11:33:47,982] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 11:33:48,291] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 11:47:51,782] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 11:47:52,156] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 12:20:10,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 12:20:11,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 12:57:11,635] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 12:57:12,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 13:21:57,116] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 13:21:57,304] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 13:38:57,159] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 13:38:57,581] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 13:47:40,927] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 13:47:41,289] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 14:10:37,556] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 14:10:37,906] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 14:30:49,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 14:30:49,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 14:47:52,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 14:47:52,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 15:11:26,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 15:11:27,222] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 15:29:53,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 15:29:54,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 15:40:46,200] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 15:40:46,546] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 15:47:51,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 15:47:52,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 16:13:15,998] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 16:13:16,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 16:35:52,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 16:35:52,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 16:51:14,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 16:51:14,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 17:09:52,756] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 17:09:53,104] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 17:30:04,144] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 17:30:04,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 17:40:59,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 17:40:59,424] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 18:14:31,580] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 18:14:31,874] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 18:36:28,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 18:36:29,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 18:50:05,082] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 18:50:05,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 19:09:10,461] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 19:09:10,881] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 19:20:48,987] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 19:20:49,288] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 19:34:58,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 19:34:59,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 19:47:39,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 19:47:40,062] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 20:11:38,368] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 20:11:38,742] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 20:28:23,328] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 20:28:23,684] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 20:38:19,148] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 20:38:19,570] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 20:47:37,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 20:47:37,958] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 21:09:59,778] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 21:10:00,149] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 21:25:23,573] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 21:25:23,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 21:34:06,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 21:34:06,406] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 21:47:39,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 21:47:39,847] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 22:10:58,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 22:10:59,030] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 22:30:41,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 22:30:41,480] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 22:47:41,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 22:47:42,389] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 23:10:59,888] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 23:11:00,089] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 23:26:49,164] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 23:26:49,534] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 23:35:40,628] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 23:35:40,873] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-03 23:47:55,292] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-03 23:47:55,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 00:51:47,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 00:51:47,365] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 02:13:29,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 02:13:29,944] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 02:57:32,253] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 02:57:32,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 03:20:02,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 03:20:02,366] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 03:40:11,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 03:40:11,431] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 03:48:10,563] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 03:48:10,934] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 04:13:22,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 04:13:22,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 04:32:54,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 04:32:55,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 04:48:04,889] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 04:48:09,332] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 05:11:17,490] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 05:11:17,891] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 05:31:00,519] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 05:31:00,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 05:47:44,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 05:47:45,019] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 06:15:36,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 06:15:36,859] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 06:43:40,699] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 06:43:40,914] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 06:52:40,411] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 06:52:40,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 07:10:39,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 07:10:39,540] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 07:26:03,975] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 07:26:04,356] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 07:35:00,739] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 07:35:01,080] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 07:47:44,380] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 07:47:44,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 08:14:20,396] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 08:14:20,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 08:34:13,874] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 08:34:14,229] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 08:49:54,692] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 08:49:55,122] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 09:11:02,873] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 09:11:03,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 09:28:43,389] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 09:28:43,684] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 09:40:13,306] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 09:40:13,610] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 09:47:40,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 09:47:40,730] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 10:11:10,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 10:11:10,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 10:33:52,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 10:33:52,604] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 10:47:40,273] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 10:47:40,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 11:09:23,235] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 11:09:23,564] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 11:21:43,928] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 11:21:44,334] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 11:34:10,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 11:34:10,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 11:47:41,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 11:47:41,713] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 12:19:47,411] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 12:19:47,766] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 12:56:39,816] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 12:56:40,159] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 13:21:04,077] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 13:21:04,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 13:38:22,793] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 13:38:23,163] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 13:47:42,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 13:47:43,305] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 14:11:03,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 14:11:03,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 14:30:38,227] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 14:30:38,436] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 14:47:43,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 14:47:43,384] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 15:11:22,747] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 15:11:23,125] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 15:29:25,530] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 15:29:25,958] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 15:39:30,656] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 15:39:31,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 15:47:52,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 15:47:53,158] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 16:13:58,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 16:13:59,120] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 16:36:04,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 16:36:05,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 16:50:41,233] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 16:50:41,579] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 17:09:40,091] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 17:09:40,522] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 17:28:19,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 17:28:19,788] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 17:37:49,268] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 17:37:49,662] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 17:47:47,025] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 17:47:47,389] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 18:14:24,556] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 18:14:24,988] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 18:35:54,802] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 18:35:55,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 18:49:23,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 18:49:23,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 19:08:51,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 19:08:52,327] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 19:22:44,671] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 19:22:45,114] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 19:33:52,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 19:33:52,689] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 19:47:52,571] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 19:47:52,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 20:12:05,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 20:12:05,472] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 20:28:26,790] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 20:28:27,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 20:37:52,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 20:37:53,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 20:47:49,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 20:47:49,644] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 21:09:42,748] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 21:09:43,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 21:25:02,692] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 21:25:03,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 21:33:33,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 21:33:34,308] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 21:47:39,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 21:47:40,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 22:10:19,393] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 22:10:19,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 22:29:31,745] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 22:29:32,170] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 22:40:02,093] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 22:40:02,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 22:47:36,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 22:47:36,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 23:10:09,202] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 23:10:09,570] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 23:25:29,323] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 23:25:29,737] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 23:33:34,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 23:33:34,501] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-04 23:47:39,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-04 23:47:40,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 00:50:53,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 00:50:54,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 02:11:20,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 02:11:20,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 02:54:07,087] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 02:54:07,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 03:15:05,797] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 03:15:06,061] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 03:33:50,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 03:33:51,172] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 03:47:42,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 03:47:43,125] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 04:13:31,048] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 04:13:31,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 04:32:32,956] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 04:32:33,328] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 04:47:47,103] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 04:47:47,405] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 05:10:07,625] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 05:10:07,941] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 05:29:26,835] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 05:29:27,140] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 05:39:24,224] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 05:39:24,596] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 05:47:51,708] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 05:47:52,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 06:14:12,393] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 06:14:12,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 06:35:06,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 06:35:06,799] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 06:48:38,512] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 06:48:38,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 07:11:08,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 07:11:09,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 07:25:49,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 07:25:49,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 07:34:14,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 07:34:14,526] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 07:47:53,388] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 07:47:53,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 08:13:13,694] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 08:13:14,059] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 08:31:51,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 08:31:51,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 08:48:04,383] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 08:48:04,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 09:12:59,651] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 09:13:03,948] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 09:29:39,290] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 09:29:39,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 09:39:04,514] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 09:39:04,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 09:47:58,487] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 09:47:58,696] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 10:10:05,235] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 10:10:05,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 10:30:07,872] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 10:30:08,141] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 10:40:24,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 10:40:24,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 10:47:53,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 10:47:53,686] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 11:08:14,392] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 11:08:14,739] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 11:22:44,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 11:22:44,835] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 11:34:29,970] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 11:34:30,385] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 11:47:42,248] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 11:47:42,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 12:18:39,350] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 12:18:39,696] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 12:53:26,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 12:53:27,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 13:15:12,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 13:15:12,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 13:29:51,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 13:29:51,313] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 13:37:58,650] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 13:37:58,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 13:47:44,076] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 13:47:44,418] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 14:09:08,247] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 14:09:08,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 14:27:36,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 14:27:37,102] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 14:37:03,075] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 14:37:03,462] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 14:47:42,903] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 14:47:43,228] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 15:10:30,182] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 15:10:30,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 15:27:02,021] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 15:27:02,394] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 15:35:45,870] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 15:35:46,218] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 15:47:42,735] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 15:47:43,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 16:12:11,619] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 16:12:11,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 16:32:55,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 16:32:55,425] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 16:48:11,037] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 16:48:11,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 17:09:59,966] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 17:10:00,323] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 17:28:20,814] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 17:28:21,156] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 17:37:32,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 17:37:32,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 17:47:38,290] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 17:47:38,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 18:12:49,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 18:12:49,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 18:32:57,567] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 18:32:57,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 18:47:40,465] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 18:47:40,833] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 19:08:35,441] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 19:08:35,730] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 19:21:57,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 19:21:57,652] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 19:33:39,196] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 19:33:39,563] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 19:47:37,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 19:47:37,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 20:10:40,331] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 20:10:40,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 20:26:22,327] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 20:26:22,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 20:34:54,638] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 20:34:54,985] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 20:47:43,895] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 20:47:44,183] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 21:09:07,899] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 21:09:08,370] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 21:25:55,776] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 21:25:55,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 21:35:46,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 21:35:47,279] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 21:47:29,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 21:47:29,966] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 22:10:18,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 22:10:18,452] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 22:29:44,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 22:29:44,679] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 22:40:06,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 22:40:06,721] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 22:47:27,350] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 22:47:27,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 23:10:05,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 23:10:05,798] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 23:24:50,564] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 23:24:50,896] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 23:33:38,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 23:33:39,307] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-05 23:47:44,936] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-05 23:47:45,296] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 00:55:37,664] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 00:55:38,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 02:19:29,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 02:19:30,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 03:05:29,622] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 03:05:29,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 03:35:40,530] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 03:35:40,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 03:49:07,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 03:49:08,375] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 04:13:28,556] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 04:13:28,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 04:32:36,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 04:32:36,483] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 04:47:46,551] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 04:47:46,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 05:10:17,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 05:10:18,184] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 05:28:43,692] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 05:28:43,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 05:38:29,949] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 05:38:30,366] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 05:47:40,609] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 05:47:41,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 06:14:11,956] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 06:14:12,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 06:35:37,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 06:35:37,906] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 06:48:39,605] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 06:48:39,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 07:11:18,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 07:11:18,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 07:24:33,070] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 07:24:33,481] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 07:33:24,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 07:33:25,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 07:47:44,727] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 07:47:45,101] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 08:12:48,774] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 08:12:49,114] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 08:31:25,247] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 08:31:25,624] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 08:47:41,592] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 08:47:41,937] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 09:11:10,373] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 09:11:10,860] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 09:27:09,177] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 09:27:09,537] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 09:35:22,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 09:35:22,499] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 09:47:46,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 09:47:47,226] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 10:10:39,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 10:10:39,517] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 10:32:17,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 10:32:17,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 10:47:36,362] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 10:47:36,786] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 11:09:11,671] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 11:09:12,054] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 11:22:41,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 11:22:41,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 11:34:58,951] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 11:34:59,299] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 11:47:59,615] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 11:47:59,959] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 12:18:12,819] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 12:18:13,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 12:53:26,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 12:53:27,200] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 13:15:19,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 13:15:19,847] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 13:30:02,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 13:30:02,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 13:38:11,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 13:38:11,957] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 13:47:48,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 13:47:48,808] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 14:09:06,642] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 14:09:06,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 14:27:44,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 14:27:45,162] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 14:37:36,977] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 14:37:37,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 14:47:47,159] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 14:47:47,586] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 15:10:35,657] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 15:10:36,030] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 15:26:53,801] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 15:26:54,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 15:35:52,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 15:35:52,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 15:47:52,655] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 15:47:53,024] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 16:11:43,345] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 16:11:43,634] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 16:32:00,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 16:32:01,003] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 16:47:37,971] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 16:47:38,277] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 17:09:12,951] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 17:09:13,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 17:28:14,914] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 17:28:15,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 17:37:59,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 17:38:00,134] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 17:47:40,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 17:47:41,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 18:12:52,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 18:12:52,534] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 18:32:58,794] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 18:32:59,095] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 18:47:29,615] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 18:47:29,911] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 19:08:39,618] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 19:08:39,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 19:21:42,072] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 19:21:42,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 19:34:11,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 19:34:12,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 19:47:41,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 19:47:41,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 20:10:53,816] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 20:10:54,230] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 20:26:40,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 20:26:41,017] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 20:35:19,001] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 20:35:19,348] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 20:47:50,447] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 20:47:50,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 21:09:21,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 21:09:21,449] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 21:24:16,975] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 21:24:17,394] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 21:33:35,066] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 21:33:35,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 21:47:38,462] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 21:47:38,750] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 22:09:38,599] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 22:09:39,012] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 22:28:51,197] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 22:28:51,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 22:38:47,970] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 22:38:48,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 22:47:46,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 22:47:46,872] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 23:09:57,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 23:09:58,350] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 23:26:08,012] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 23:26:08,356] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 23:36:11,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 23:36:12,050] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-06 23:47:54,207] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-06 23:47:54,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 00:53:29,666] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 00:53:29,875] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 02:16:25,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 02:16:26,201] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 03:04:11,116] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 03:04:11,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 03:35:20,902] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 03:35:21,286] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 03:49:49,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 03:49:50,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 04:13:43,550] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 04:13:43,900] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 04:33:46,822] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 04:33:47,192] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 04:48:32,983] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 04:48:33,267] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 05:12:26,883] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 05:12:27,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 05:32:01,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 05:32:02,273] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 05:47:49,839] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 05:47:50,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 06:16:04,449] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 06:16:04,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 06:43:47,171] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 06:43:47,608] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 06:52:11,325] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 06:52:11,678] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 07:11:40,622] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 07:11:40,984] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 07:26:32,949] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 07:26:33,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 07:34:47,251] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 07:34:47,539] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 07:47:42,974] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 07:47:43,268] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 08:13:44,544] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 08:13:44,994] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 08:35:22,778] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 08:35:23,118] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 08:51:14,290] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 08:51:14,496] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 09:12:25,480] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 09:12:25,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 09:30:34,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 09:30:35,181] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 09:47:41,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 09:47:41,632] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 10:12:50,564] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 10:12:50,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 10:34:34,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 10:34:34,440] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 10:48:47,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 10:48:47,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 11:10:59,980] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 11:11:00,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 11:25:31,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 11:25:31,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 11:34:07,488] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 11:34:07,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 11:47:42,122] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 11:47:42,435] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 12:20:59,781] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 12:21:00,005] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 12:58:11,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 12:58:12,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 13:24:18,039] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 13:24:18,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 13:39:58,145] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 13:39:58,552] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 13:47:42,066] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 13:47:42,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 14:10:42,459] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 14:10:42,833] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 14:30:53,777] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 14:30:54,279] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 14:47:44,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 14:47:45,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 15:11:57,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 15:11:58,001] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 15:29:38,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 15:29:39,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 15:40:22,456] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 15:40:22,764] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 15:47:40,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 15:47:41,065] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 16:13:04,610] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 16:13:04,835] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 16:35:07,696] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 16:35:08,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-10-07 16:51:07,656] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-10-07 16:51:08,044] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
