[2024-07-01 00:49:31,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 00:49:32,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:05:26,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:05:26,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:45:29,679] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:45:30,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:11:23,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:11:23,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:28:31,461] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:28:31,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:38:06,049] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:38:06,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
