[2024-12-01 01:05:17,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 01:05:18,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 02:54:37,332] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 02:54:37,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 03:39:13,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 03:39:13,697] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:02:13,584] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:02:13,941] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:34:58,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:34:58,577] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:50:27,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:50:27,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:11:23,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:11:24,245] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:30:58,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:30:58,455] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:47:39,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:47:39,552] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:15:47,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:15:47,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:44:07,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:44:08,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:53:05,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:53:06,113] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:10:39,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:10:39,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:27:39,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:27:39,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:37:58,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:37:58,669] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:47:40,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:47:41,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:13:51,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:13:52,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:33:39,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:33:39,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:49:52,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:49:53,094] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:11:06,695] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:11:07,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:27:42,748] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:27:43,097] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:37:06,163] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:37:06,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:47:32,348] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:47:32,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:11:45,086] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:11:45,483] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:33:30,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:33:31,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:47:48,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:47:49,123] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:09:12,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:09:12,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:23:02,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:23:03,022] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:33:40,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:33:40,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:47:55,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:47:55,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:20:15,106] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:20:15,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:56:58,875] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:56:59,241] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:21:26,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:21:26,665] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:38:43,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:38:43,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:47:50,511] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:47:50,913] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:09:25,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:09:25,893] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:29:13,943] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:29:14,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
