[2024-11-01 00:56:34,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 00:56:34,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 02:23:04,660] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 02:23:04,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:10:25,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:10:25,413] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:41:01,534] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:41:01,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
