[2024-11-01 00:56:34,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 00:56:34,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 02:23:04,660] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 02:23:04,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:10:25,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:10:25,413] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:41:01,534] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:41:01,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:53:11,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:53:12,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:13:35,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:13:35,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:33:16,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:33:16,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:48:39,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:48:40,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:11:43,846] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:11:44,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:30:44,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:30:44,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:47:43,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:47:44,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:16:26,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:16:26,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:44:30,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:44:31,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:52:57,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:52:57,916] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:11:03,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:11:08,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:27:23,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:27:23,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:36:23,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:36:23,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:47:34,728] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:47:35,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:14:22,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:14:22,956] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:33:08,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:33:08,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:49:13,172] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:49:13,479] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:11:49,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:11:50,184] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:28:36,270] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:28:36,617] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:38:35,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:38:35,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:47:46,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:47:47,144] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:12:25,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:12:26,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:34:15,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:34:16,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:47:44,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:47:44,612] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:09:32,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:09:33,050] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:23:19,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:23:19,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:33:38,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:33:39,198] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:47:56,501] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:47:56,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:20:03,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:20:03,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:55:20,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:55:21,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:18:50,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:18:50,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:38:16,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:38:16,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:47:48,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:47:48,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:10:30,730] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:10:31,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:29:41,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:29:42,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:40:40,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:40:40,585] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:48:04,286] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:48:04,647] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:11:30,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:11:30,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:30:06,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:30:07,191] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:40:46,843] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:40:47,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:48:09,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:48:09,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:12:56,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:12:56,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:34:01,691] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:34:02,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:49:41,523] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:49:41,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:10:13,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:10:13,558] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:28:56,174] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:28:56,554] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:38:55,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:38:56,351] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:47:46,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:47:47,317] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:14:34,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:14:34,864] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:35:34,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:35:34,884] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:49:53,964] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:49:54,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:09:18,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:09:18,388] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:23:53,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:23:54,055] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:35:17,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:35:17,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:47:46,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:47:46,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:12:18,181] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:12:18,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:28:47,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:28:48,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:38:30,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:38:31,208] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:47:55,408] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:47:55,826] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:10:15,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:10:15,573] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:25:23,901] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:25:24,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:33:48,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:33:48,632] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:47:40,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:47:41,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:10:28,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:10:29,056] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:29:53,379] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:29:53,783] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:40:35,523] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:40:35,893] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:47:52,994] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:47:53,321] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:10:47,767] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:10:48,180] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:26:09,329] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:26:09,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:35:01,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:35:01,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:47:42,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:47:43,233] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 00:51:16,915] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 00:51:17,223] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 02:11:20,989] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 02:11:21,282] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 02:54:23,837] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 02:54:24,179] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:15:45,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:15:45,585] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:39:35,761] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:39:36,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:47:37,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:47:37,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:13:35,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:13:35,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:33:03,552] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:33:03,946] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:48:18,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:48:19,108] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:11:08,747] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:11:09,093] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:29:41,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:29:41,553] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:40:00,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:40:01,806] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:47:43,990] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:47:44,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:15:16,110] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:15:16,467] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:36:12,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:36:13,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:49:56,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:49:56,438] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:09:41,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:09:41,951] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:25:46,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:25:47,109] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:33:51,008] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:33:51,305] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:47:49,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:47:49,631] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 08:13:32,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 08:13:32,354] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 08:31:49,681] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 08:31:50,061] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 08:47:54,745] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 08:47:55,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 09:10:25,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 09:10:25,645] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 09:26:38,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 09:26:39,197] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 09:35:50,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 09:35:51,002] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 09:47:46,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 09:47:46,282] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 10:10:36,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 10:10:37,007] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 10:30:20,008] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 10:30:20,336] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 10:40:49,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 10:40:49,702] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 10:48:23,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 10:48:23,594] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 11:08:28,644] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 11:08:29,002] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 11:21:53,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 11:21:53,640] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 11:33:33,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 11:33:33,512] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 11:47:43,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 11:47:44,189] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 12:18:44,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 12:18:44,512] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 12:53:45,193] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 12:53:45,516] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 13:15:42,186] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 13:15:42,571] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 13:34:39,234] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 13:34:39,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 13:47:47,952] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 13:47:48,302] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 14:09:16,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 14:09:17,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 14:27:40,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 14:27:40,857] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 14:37:09,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 14:37:10,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 14:47:37,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 14:47:37,617] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 15:11:27,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 15:11:27,835] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 15:29:11,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 15:29:11,916] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 15:38:36,959] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 15:38:37,367] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 15:47:42,749] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 15:47:43,137] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 16:11:54,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 16:11:55,148] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 16:33:22,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 16:33:22,355] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 16:49:37,504] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 16:49:37,926] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 17:09:14,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 17:09:15,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 17:26:43,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 17:26:44,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 17:35:16,679] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 17:35:16,950] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 17:47:49,773] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 17:47:50,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 18:13:21,005] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 18:13:21,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 18:33:18,745] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 18:33:19,062] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 18:47:38,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 18:47:39,037] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 19:08:43,528] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 19:08:43,894] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 19:23:22,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 19:23:23,183] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 19:33:16,370] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 19:33:16,721] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 19:47:49,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 19:47:49,684] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 20:12:11,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 20:12:11,790] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 20:27:40,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 20:27:40,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 20:36:21,143] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 20:36:21,498] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 20:47:54,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 20:47:54,896] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 21:10:04,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 21:10:04,625] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 21:25:12,539] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 21:25:12,754] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 21:33:41,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 21:33:41,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 21:47:41,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 21:47:41,808] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 22:10:45,062] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 22:10:45,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 22:29:22,333] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 22:29:22,695] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 22:39:48,231] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 22:39:48,594] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 22:47:41,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 22:47:41,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 23:12:31,906] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 23:12:32,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 23:28:03,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 23:28:04,232] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 23:37:23,323] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 23:37:23,702] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 23:47:42,206] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 23:47:42,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 00:55:58,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 00:55:58,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 02:19:48,076] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 02:19:48,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 03:06:29,124] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 03:06:29,499] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 03:36:50,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 03:36:50,974] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 03:50:11,793] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 03:50:12,217] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 04:13:18,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 04:13:18,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 04:31:59,194] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 04:31:59,612] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 04:47:45,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 04:47:45,635] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 05:10:32,669] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 05:10:33,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 05:28:38,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 05:28:39,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 05:38:34,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 05:38:35,135] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 05:47:33,081] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 05:47:33,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 06:16:10,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 06:16:10,638] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 06:42:53,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 06:42:53,824] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 06:50:51,081] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 06:50:51,499] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 07:09:56,218] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 07:09:56,643] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 07:26:27,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 07:26:28,295] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 07:35:26,681] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 07:35:27,064] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 07:47:52,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 07:47:53,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 08:12:53,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 08:12:54,029] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 08:30:23,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 08:30:23,340] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 08:41:20,021] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 08:41:20,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 08:48:33,928] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 08:48:34,334] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 09:11:06,705] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 09:11:07,106] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 09:27:23,371] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 09:27:23,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 09:36:28,457] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 09:36:28,757] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 09:47:43,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 09:47:43,467] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 10:12:29,418] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 10:12:29,636] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 10:33:04,469] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 10:33:04,812] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 10:47:44,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 10:47:44,473] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 11:09:06,809] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 11:09:07,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 11:22:58,416] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 11:22:58,768] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 11:33:49,343] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 11:33:49,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 11:47:56,392] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 11:47:56,716] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 12:18:22,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 12:18:22,910] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 12:52:57,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 12:52:57,377] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 13:15:43,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 13:15:43,380] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 13:34:51,148] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 13:34:51,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 13:47:41,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 13:47:42,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 14:10:42,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 14:10:43,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 14:29:12,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 14:29:12,765] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 14:39:20,108] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 14:39:20,522] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 14:47:58,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 14:47:58,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 15:10:03,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 15:10:04,076] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 15:26:27,441] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 15:26:27,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 15:35:16,564] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 15:35:16,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 15:47:42,638] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 15:47:42,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 16:12:22,583] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 16:12:22,819] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 16:32:18,592] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 16:32:18,946] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 16:47:39,272] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 16:47:39,676] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 17:09:01,035] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 17:09:01,439] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-03 17:26:51,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-03 17:26:52,098] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
