[2024-12-01 01:05:17,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 01:05:18,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 02:54:37,332] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 02:54:37,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 03:39:13,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 03:39:13,697] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:02:13,584] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:02:13,941] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:34:58,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:34:58,577] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:50:27,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:50:27,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:11:23,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:11:24,245] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:30:58,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:30:58,455] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:47:39,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:47:39,552] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:15:47,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:15:47,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:44:07,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:44:08,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:53:05,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:53:06,113] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:10:39,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:10:39,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:27:39,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:27:39,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:37:58,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:37:58,669] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:47:40,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:47:41,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:13:51,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:13:52,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:33:39,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:33:39,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:49:52,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:49:53,094] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:11:06,695] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:11:07,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:27:42,748] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:27:43,097] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:37:06,163] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:37:06,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:47:32,348] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:47:32,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:11:45,086] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:11:45,483] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:33:30,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:33:31,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:47:48,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:47:49,123] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:09:12,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:09:12,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:23:02,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:23:03,022] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:33:40,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:33:40,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:47:55,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:47:55,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:20:15,106] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:20:15,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:56:58,875] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:56:59,241] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:21:26,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:21:26,665] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:38:43,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:38:43,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:47:50,511] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:47:50,913] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:09:25,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:09:25,893] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:29:13,943] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:29:14,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:39:56,600] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:39:57,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:47:43,558] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:47:43,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:10:18,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:10:18,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:27:56,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:27:56,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:37:26,599] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:37:26,936] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:47:32,535] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:47:32,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:12:49,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:12:49,665] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:34:27,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:34:27,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:49:57,764] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:49:58,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:09:35,758] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:09:36,118] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:27:56,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:27:57,155] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:37:43,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:37:43,678] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:47:38,053] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:47:38,371] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:14:04,064] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:14:04,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:36:00,742] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:36:02,251] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:49:45,493] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:49:45,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:08:22,540] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:08:22,978] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:21:47,233] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:21:47,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:33:50,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:33:51,076] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:47:47,131] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:47:47,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:11:46,864] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:11:47,244] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:28:59,628] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:28:59,989] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:39:26,758] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:39:27,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:47:36,067] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:47:36,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:09:59,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:10:00,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:25:42,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:25:42,760] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:34:13,569] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:34:13,976] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:47:58,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:47:58,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:10:21,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:10:21,557] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:30:35,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:30:36,011] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:47:35,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:47:35,787] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:10:42,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:10:42,672] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:26:46,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:26:47,324] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:36:00,984] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:36:02,168] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:47:40,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:47:41,107] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 00:57:53,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 00:57:54,278] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 02:27:39,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 02:27:39,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 03:23:58,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 03:23:58,804] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 03:49:41,810] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 03:49:42,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:14:21,188] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:14:21,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:35:54,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:35:54,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:50:58,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:50:59,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:12:34,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:12:34,626] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:32:42,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:32:43,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:47:44,913] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:47:45,265] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 06:17:26,983] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 06:17:27,395] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 06:46:25,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 06:46:25,744] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 07:12:21,435] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:12:21,826] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 07:30:00,488] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:30:03,668] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 07:41:36,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:41:38,663] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 07:48:56,354] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:48:58,870] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:16:44,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:16:46,770] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:44:21,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:44:23,389] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:55:03,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:55:05,749] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:13:30,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:13:33,022] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:33:55,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:33:59,241] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:47:56,311] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:47:59,401] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:13:36,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:13:38,308] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:37:38,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:37:41,721] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:50:57,313] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:51:01,212] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:10:13,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:10:15,920] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:25:01,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:25:03,849] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:34:04,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:34:07,639] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:47:47,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:47:50,604] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 12:23:06,056] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 12:23:08,917] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 13:02:02,544] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 13:02:05,030] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
