[2024-08-01 00:49:58,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 00:49:59,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:06:52,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:06:52,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:46:31,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:46:31,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:11:29,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:11:30,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:28:31,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:28:31,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:37:38,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:37:38,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:47:57,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:47:58,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:12:12,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:12:12,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:29:26,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:29:26,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:39:00,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:39:01,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:47:46,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:47:46,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:09:59,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:09:59,830] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:27:49,134] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:27:49,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:36:18,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:36:19,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:47:38,336] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:47:38,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:14:08,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:14:08,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:33:57,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:33:57,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:47:38,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:47:38,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:09:41,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:09:42,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:22:07,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:22:07,616] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:33:27,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:33:28,129] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
