[2024-08-01 00:49:58,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 00:49:59,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:06:52,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:06:52,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:46:31,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:46:31,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:11:29,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:11:30,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:28:31,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:28:31,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:37:38,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:37:38,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:47:57,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:47:58,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:12:12,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:12:12,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:29:26,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:29:26,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:39:00,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:39:01,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:47:46,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:47:46,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:09:59,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:09:59,830] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:27:49,134] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:27:49,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:36:18,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:36:19,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:47:38,336] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:47:38,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:14:08,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:14:08,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:33:57,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:33:57,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:47:38,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:47:38,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:09:41,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:09:42,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:22:07,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:22:07,616] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:33:27,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:33:28,129] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:47:57,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:47:57,606] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:12:59,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:12:59,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:30:34,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:30:35,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:47:52,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:47:52,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:09:49,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:09:49,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:25:09,777] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:25:10,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:33:19,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:33:20,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:47:44,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:47:45,128] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:11:30,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:11:31,096] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:30:34,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:30:35,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:47:31,561] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:47:31,989] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:09:11,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:09:11,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:22:30,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:22:30,481] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:33:22,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:33:23,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:47:59,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:48:00,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:18:07,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:18:08,302] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:51:46,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:51:46,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:14:00,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:14:00,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:27:58,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:27:58,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:35:18,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:35:19,244] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:47:42,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:47:42,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:09:28,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:09:28,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:27:39,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:27:39,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:36:45,032] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:36:45,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:47:40,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:47:40,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:10:11,167] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:10:11,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:26:01,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:26:01,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:33:43,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:33:44,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:47:58,234] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:47:58,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:12:04,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:12:05,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:32:05,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:32:05,441] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:47:47,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:47:47,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:10:30,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:10:30,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:28:12,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:28:12,641] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:35:25,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:35:25,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:47:52,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:47:53,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:12:41,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:12:41,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:31:49,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:31:49,673] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:47:35,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:47:35,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:07:42,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:07:42,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:19:24,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:19:24,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:32:59,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:33:00,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:47:45,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:47:45,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:11:24,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:11:24,738] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:26:09,764] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:26:10,150] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:35:51,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:35:51,882] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:47:39,634] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:47:40,065] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:10:33,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:10:33,899] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:25:30,207] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:25:30,581] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:33:25,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:33:26,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:47:53,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:47:53,505] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:08:55,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:08:55,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:27:15,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:27:15,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:35:49,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:35:49,716] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:47:31,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:47:32,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:09:37,567] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:09:38,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:24:58,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:24:58,565] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:33:30,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:33:31,218] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:48:01,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:48:01,677] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 00:44:25,992] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 00:44:26,322] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 01:50:52,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 01:50:53,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 02:30:21,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 02:30:21,742] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 02:49:03,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 02:49:03,763] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:11:14,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:11:14,809] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:28:55,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:28:55,904] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:38:19,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:38:19,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:47:49,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:47:49,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:12:07,140] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:12:07,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:31:31,545] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:31:31,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:47:26,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:47:26,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:09:39,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:09:39,710] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:28:25,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:28:25,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:37:12,147] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:37:12,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:47:36,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:47:36,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:15:23,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:15:23,620] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:35:40,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:35:40,513] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:48:45,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:48:45,456] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:10:49,790] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:10:50,151] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:23:11,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:23:12,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:33:16,900] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:33:17,393] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:47:27,569] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:47:27,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:12:37,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:12:37,917] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:31:14,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:31:14,991] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:47:49,167] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:47:49,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:11:00,935] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:11:01,161] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:26:36,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:26:36,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:34:18,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:34:18,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:47:55,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:47:56,152] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:10:22,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:10:22,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:29:44,288] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:29:44,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:39:03,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:39:03,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:47:38,644] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:47:38,937] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:08:36,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:08:37,084] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:21:09,444] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:21:09,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:33:05,390] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:33:05,820] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:47:53,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:47:54,283] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 12:17:26,726] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 12:17:26,952] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 12:50:59,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 12:50:59,756] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:12:58,599] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:12:58,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:27:03,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:27:03,427] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:34:44,439] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:34:44,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:47:56,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:47:56,775] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:09:23,331] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:09:23,619] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:27:02,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:27:03,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:35:47,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:35:47,710] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:47:29,489] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:47:29,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:09:59,374] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:09:59,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:25:48,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:25:48,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:33:30,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:33:30,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:47:46,056] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:47:46,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:11:55,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:11:55,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:33:03,605] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:33:03,923] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:47:40,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:47:40,540] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:09:14,582] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:09:15,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:26:03,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:26:03,406] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:33:34,232] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:33:34,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:47:51,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:47:52,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:13:24,633] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:13:25,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:32:19,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:32:19,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:47:46,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:47:46,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:07:34,583] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:07:34,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:20:19,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:20:19,688] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:34:05,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:34:06,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:47:40,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:47:41,122] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:10:58,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:10:58,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:26:07,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:26:08,264] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:33:36,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:33:36,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:47:33,256] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:47:33,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:09:57,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:09:57,839] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:23:32,829] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:23:33,273] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:33:19,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:33:19,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:47:50,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:47:50,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 22:10:02,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 22:10:03,277] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 22:27:38,250] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 22:27:38,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 22:36:16,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 22:36:16,424] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 22:47:35,836] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 22:47:36,161] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 23:09:38,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 23:09:38,645] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 23:23:03,278] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 23:23:03,654] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 23:33:58,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 23:33:58,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 23:47:43,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 23:47:44,202] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 00:43:43,681] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 00:43:44,066] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 01:48:35,895] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 01:48:36,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 02:28:49,201] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 02:28:49,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 02:46:09,747] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 02:46:10,120] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 03:10:30,656] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 03:10:30,884] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 03:26:39,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 03:26:39,606] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 03:35:10,326] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 03:35:10,565] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 03:47:36,010] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 03:47:36,346] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 04:11:41,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 04:11:41,894] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 04:28:35,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 04:28:35,557] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 04:37:59,050] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 04:37:59,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 04:47:27,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 04:47:27,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 05:09:09,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 05:09:10,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 05:26:08,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 05:26:08,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 05:33:53,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 05:33:53,559] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 05:47:55,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 05:47:55,449] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 06:13:46,248] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 06:13:46,822] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 06:32:25,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 06:32:26,049] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 06:47:43,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 06:47:44,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 07:08:41,376] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 07:08:41,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 07:20:45,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 07:20:46,162] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 07:33:02,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 07:33:02,828] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 07:47:46,325] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 07:47:46,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 08:12:30,450] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 08:12:30,767] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 08:29:17,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 08:29:17,796] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 08:38:17,847] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 08:38:18,140] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 08:47:49,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 08:47:49,769] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 09:10:07,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 09:10:07,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 09:27:15,019] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 09:27:15,415] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 09:34:52,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 09:34:52,984] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 09:47:38,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 09:47:38,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 10:09:23,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 10:09:24,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 10:28:14,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 10:28:15,453] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 10:36:29,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 10:36:29,812] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 10:47:42,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 10:47:42,367] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 11:08:25,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 11:08:25,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 11:20:35,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 11:20:35,775] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 11:32:55,082] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 11:32:55,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 11:47:32,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 11:47:33,240] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 12:16:02,435] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 12:16:02,822] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 12:48:10,134] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 12:48:10,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 13:10:10,288] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 13:10:10,482] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 13:24:04,514] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 13:24:04,924] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 13:33:10,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 13:33:11,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 13:47:39,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 13:47:40,214] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 14:10:23,839] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 14:10:24,168] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 14:27:05,635] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 14:27:05,851] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 14:35:23,131] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 14:35:23,427] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 14:47:43,659] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 14:47:44,034] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 15:08:43,880] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 15:08:44,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 15:25:31,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 15:25:31,918] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 15:33:16,591] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 15:33:16,808] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 15:47:37,751] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 15:47:38,188] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 16:11:06,441] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 16:11:06,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 16:31:03,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 16:31:03,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 16:47:42,189] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 16:47:42,512] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 17:08:52,182] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 17:08:52,604] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 17:24:40,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 17:24:41,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 17:34:02,863] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 17:34:03,339] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 17:47:49,358] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 17:47:49,739] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 18:12:32,957] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 18:12:33,343] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 18:31:04,998] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 18:31:05,312] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 18:47:55,970] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 18:47:56,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 19:07:31,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 19:07:31,900] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 19:19:08,774] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 19:19:09,096] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 19:32:55,992] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 19:32:56,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 19:47:44,393] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 19:47:44,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 20:09:30,664] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 20:09:30,983] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 20:23:40,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 20:23:40,771] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 20:34:04,821] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 20:34:05,147] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 20:47:33,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 20:47:33,689] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 21:09:26,035] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 21:09:26,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 21:22:37,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 21:22:37,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 21:33:44,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 21:33:45,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 21:47:51,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 21:47:51,568] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 22:08:21,459] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 22:08:21,774] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 22:26:23,605] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 22:26:23,995] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 22:34:13,282] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 22:34:13,654] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 22:47:38,499] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 22:47:38,869] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 23:10:26,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 23:10:26,920] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 23:24:58,155] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 23:24:58,367] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 23:34:22,043] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 23:34:22,354] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-03 23:47:28,563] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-03 23:47:28,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 00:49:19,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 00:49:19,664] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 02:04:53,420] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 02:04:53,737] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 02:44:24,573] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 02:44:24,900] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 02:54:31,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 02:54:31,414] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 03:10:51,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 03:10:52,182] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 03:27:28,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 03:27:29,102] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 03:36:24,915] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 03:36:25,313] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 03:47:34,847] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 03:47:35,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 04:13:13,604] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 04:13:13,972] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 04:31:41,221] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 04:31:41,543] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 04:47:47,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 04:47:47,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 05:09:26,910] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 05:09:27,343] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 05:26:14,482] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 05:26:14,705] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 05:33:58,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 05:33:59,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 05:47:47,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 05:47:47,502] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 06:12:47,990] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 06:12:48,210] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 06:31:52,033] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 06:31:52,416] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 06:47:43,844] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 06:47:44,250] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 07:09:37,896] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 07:09:38,281] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 07:21:41,984] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 07:21:42,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 07:33:18,812] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 07:33:19,189] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 07:47:37,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 07:47:37,873] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 08:11:24,935] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 08:11:25,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 08:28:13,201] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 08:28:13,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 08:37:12,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 08:37:12,792] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 08:47:47,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 08:47:47,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 09:09:53,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 09:09:53,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 09:25:55,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 09:25:56,230] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 09:33:20,428] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 09:33:20,716] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 09:47:53,669] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 09:47:54,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 10:09:25,083] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 10:09:25,494] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 10:28:19,190] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 10:28:19,571] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 10:36:39,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 10:36:39,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 10:47:44,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 10:47:44,874] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 11:08:55,963] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 11:08:56,334] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 11:20:40,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 11:20:41,296] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 11:33:26,248] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 11:33:26,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 11:47:27,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 11:47:28,251] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 12:15:56,614] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 12:15:56,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 12:48:07,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 12:48:08,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 13:10:49,983] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 13:10:50,348] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 13:25:13,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 13:25:14,246] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 13:32:47,204] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 13:32:47,513] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 13:47:38,613] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 13:47:38,938] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 14:09:21,846] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 14:09:22,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 14:27:52,923] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 14:27:53,120] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 14:36:45,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 14:36:45,667] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 14:47:47,044] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 14:47:47,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 15:10:16,779] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 15:10:17,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 15:24:41,247] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 15:24:41,567] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 15:32:57,809] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 15:32:58,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 15:47:44,087] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 15:47:44,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 16:10:19,111] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 16:10:19,475] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 16:28:26,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 16:28:27,018] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 16:37:59,813] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 16:38:00,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 16:47:33,952] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 16:47:34,382] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 17:08:22,404] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 17:08:22,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 17:25:16,500] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 17:25:16,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 17:33:06,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 17:33:06,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 17:47:57,107] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 17:47:57,417] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 18:11:46,394] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 18:11:46,809] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 18:29:57,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 18:29:57,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 18:39:21,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 18:39:22,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 18:47:32,524] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 18:47:32,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 19:08:18,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 19:08:19,336] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 19:19:29,328] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 19:19:29,751] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 19:33:01,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 19:33:01,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 19:47:47,400] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 19:47:47,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 20:10:38,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 20:10:39,113] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 20:25:10,313] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 20:25:10,768] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 20:34:28,338] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 20:34:28,718] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 20:47:42,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 20:47:42,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 21:09:21,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 21:09:22,335] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 21:23:17,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 21:23:18,132] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 21:33:48,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 21:33:48,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 21:47:37,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 21:47:37,344] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 22:10:04,525] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 22:10:04,949] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 22:27:12,948] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 22:27:13,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 22:35:40,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 22:35:41,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 22:47:56,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 22:47:56,881] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 23:10:49,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 23:10:50,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 23:25:06,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 23:25:07,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 23:33:26,391] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 23:33:26,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-04 23:47:42,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-04 23:47:42,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 00:46:33,453] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 00:46:33,776] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 02:02:06,868] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 02:02:07,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 02:43:52,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 02:43:52,527] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 02:53:53,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 02:53:53,318] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 03:11:09,633] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 03:11:09,949] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 03:28:19,271] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 03:28:19,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 03:37:50,731] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 03:37:50,969] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 03:47:48,794] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 03:47:49,107] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 04:12:33,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 04:12:33,597] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 04:29:41,708] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 04:29:42,059] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 04:39:29,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 04:39:29,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 04:47:46,016] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 04:47:46,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 05:11:40,110] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 05:11:40,496] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 05:29:24,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 05:29:25,197] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 05:38:40,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 05:38:40,603] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 05:47:25,983] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 05:47:26,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 06:14:22,617] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 06:14:23,001] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 06:34:42,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 06:34:42,827] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 06:47:31,507] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 06:47:31,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 07:10:18,387] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 07:10:18,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 07:23:10,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 07:23:10,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 07:33:33,361] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 07:33:33,575] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 07:47:48,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 07:47:49,029] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 08:13:36,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 08:13:36,959] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 08:31:11,676] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 08:31:12,039] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 08:47:58,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 08:47:58,449] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 09:10:35,677] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 09:10:36,057] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 09:26:11,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 09:26:11,527] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 09:34:34,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 09:34:35,329] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 09:47:33,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 09:47:33,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 10:10:08,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 10:10:08,829] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 10:30:00,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 10:30:00,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 10:39:42,151] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 10:39:42,540] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 10:47:52,926] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 10:47:53,214] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 11:09:04,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 11:09:04,872] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 11:21:51,242] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 11:21:51,602] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 11:33:13,402] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 11:33:13,706] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 11:47:54,873] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 11:47:55,304] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 12:18:50,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 12:18:50,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 12:52:34,277] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 12:52:34,672] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 13:14:19,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 13:14:19,691] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 13:28:49,582] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 13:28:49,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 13:36:40,011] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 13:36:40,334] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 13:47:38,817] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 13:47:39,118] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 14:09:37,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 14:09:38,010] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 14:27:17,111] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 14:27:17,439] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 14:36:42,735] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 14:36:43,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 14:47:57,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 14:47:57,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 15:10:20,367] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 15:10:20,799] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 15:26:08,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 15:26:08,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 15:34:21,603] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 15:34:21,919] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 15:47:41,212] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 15:47:41,583] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 16:11:54,034] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 16:11:54,416] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 16:31:24,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 16:31:24,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 16:47:38,756] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 16:47:39,202] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 17:08:50,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 17:08:50,593] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 17:28:55,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 17:28:55,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 17:37:41,506] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 17:37:41,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 17:48:07,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 17:48:07,702] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 18:13:52,705] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 18:13:53,055] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 18:33:30,177] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 18:33:30,643] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 18:47:38,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 18:47:38,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 19:09:42,904] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 19:09:43,285] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 19:21:49,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 19:21:50,296] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 19:33:12,037] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 19:33:12,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 19:47:50,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 19:47:51,262] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-05 20:10:26,519] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-05 20:10:27,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
