[2024-08-01 00:49:58,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 00:49:59,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:06:52,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:06:52,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:46:31,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:46:31,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:11:29,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:11:30,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:28:31,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:28:31,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:37:38,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:37:38,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:47:57,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:47:58,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:12:12,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:12:12,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:29:26,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:29:26,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:39:00,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:39:01,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:47:46,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:47:46,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:09:59,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:09:59,830] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:27:49,134] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:27:49,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:36:18,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:36:19,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:47:38,336] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:47:38,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:14:08,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:14:08,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:33:57,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:33:57,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:47:38,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:47:38,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:09:41,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:09:42,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:22:07,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:22:07,616] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:33:27,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:33:28,129] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:47:57,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:47:57,606] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:12:59,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:12:59,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:30:34,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:30:35,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:47:52,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:47:52,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:09:49,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:09:49,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:25:09,777] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:25:10,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:33:19,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:33:20,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:47:44,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:47:45,128] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:11:30,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:11:31,096] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:30:34,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:30:35,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:47:31,561] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:47:31,989] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:09:11,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:09:11,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:22:30,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:22:30,481] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:33:22,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:33:23,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:47:59,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:48:00,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:18:07,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:18:08,302] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:51:46,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:51:46,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:14:00,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:14:00,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:27:58,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:27:58,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:35:18,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:35:19,244] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:47:42,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:47:42,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:09:28,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:09:28,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:27:39,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:27:39,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:36:45,032] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:36:45,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:47:40,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:47:40,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:10:11,167] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:10:11,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:26:01,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:26:01,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:33:43,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:33:44,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:47:58,234] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:47:58,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:12:04,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:12:05,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:32:05,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:32:05,441] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:47:47,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:47:47,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:10:30,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:10:30,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:28:12,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:28:12,641] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:35:25,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:35:25,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:47:52,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:47:53,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:12:41,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:12:41,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:31:49,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:31:49,673] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:47:35,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:47:35,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:07:42,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:07:42,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:19:24,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:19:24,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:32:59,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:33:00,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
