[2024-11-01 00:56:34,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 00:56:34,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 02:23:04,660] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 02:23:04,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:10:25,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:10:25,413] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:41:01,534] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:41:01,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:53:11,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:53:12,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:13:35,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:13:35,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:33:16,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:33:16,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:48:39,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:48:40,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:11:43,846] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:11:44,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:30:44,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:30:44,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:47:43,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:47:44,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:16:26,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:16:26,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:44:30,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:44:31,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:52:57,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:52:57,916] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:11:03,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:11:08,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:27:23,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:27:23,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:36:23,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:36:23,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:47:34,728] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:47:35,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:14:22,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:14:22,956] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:33:08,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:33:08,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:49:13,172] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:49:13,479] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:11:49,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:11:50,184] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:28:36,270] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:28:36,617] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:38:35,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:38:35,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:47:46,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:47:47,144] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:12:25,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:12:26,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:34:15,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:34:16,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:47:44,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:47:44,612] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:09:32,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:09:33,050] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:23:19,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:23:19,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:33:38,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:33:39,198] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:47:56,501] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:47:56,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:20:03,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:20:03,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:55:20,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:55:21,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:18:50,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:18:50,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:38:16,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:38:16,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:47:48,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:47:48,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:10:30,730] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:10:31,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:29:41,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:29:42,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:40:40,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:40:40,585] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:48:04,286] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:48:04,647] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:11:30,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:11:30,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:30:06,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:30:07,191] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:40:46,843] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:40:47,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 15:48:09,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 15:48:09,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:12:56,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:12:56,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:34:01,691] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:34:02,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 16:49:41,523] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 16:49:41,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:10:13,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:10:13,558] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:28:56,174] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:28:56,554] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:38:55,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:38:56,351] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 17:47:46,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 17:47:47,317] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:14:34,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:14:34,864] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:35:34,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:35:34,884] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 18:49:53,964] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 18:49:54,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:09:18,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:09:18,388] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:23:53,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:23:54,055] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:35:17,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:35:17,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 19:47:46,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 19:47:46,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:12:18,181] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:12:18,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:28:47,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:28:48,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:38:30,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:38:31,208] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 20:47:55,408] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 20:47:55,826] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:10:15,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:10:15,573] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:25:23,901] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:25:24,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:33:48,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:33:48,632] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 21:47:40,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 21:47:41,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:10:28,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:10:29,056] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:29:53,379] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:29:53,783] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:40:35,523] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:40:35,893] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 22:47:52,994] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 22:47:53,321] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:10:47,767] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:10:48,180] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:26:09,329] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:26:09,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:35:01,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:35:01,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 23:47:42,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 23:47:43,233] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 00:51:16,915] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 00:51:17,223] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 02:11:20,989] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 02:11:21,282] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 02:54:23,837] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 02:54:24,179] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:15:45,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:15:45,585] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:39:35,761] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:39:36,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 03:47:37,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 03:47:37,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:13:35,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:13:35,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:33:03,552] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:33:03,946] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 04:48:18,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 04:48:19,108] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:11:08,747] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:11:09,093] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:29:41,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:29:41,553] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:40:00,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:40:01,806] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 05:47:43,990] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 05:47:44,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:15:16,110] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:15:16,467] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:36:12,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:36:13,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 06:49:56,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 06:49:56,438] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:09:41,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:09:41,951] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:25:46,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:25:47,109] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:33:51,008] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:33:51,305] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 07:47:49,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 07:47:49,631] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-02 08:13:32,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-02 08:13:32,354] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
