[2024-11-01 00:56:34,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 00:56:34,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 02:23:04,660] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 02:23:04,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:10:25,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:10:25,413] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:41:01,534] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:41:01,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 03:53:11,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 03:53:12,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:13:35,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:13:35,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:33:16,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:33:16,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 04:48:39,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 04:48:40,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:11:43,846] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:11:44,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:30:44,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:30:44,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 05:47:43,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 05:47:44,015] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:16:26,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:16:26,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:44:30,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:44:31,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 06:52:57,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 06:52:57,916] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:11:03,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:11:08,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:27:23,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:27:23,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:36:23,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:36:23,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 07:47:34,728] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 07:47:35,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:14:22,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:14:22,956] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:33:08,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:33:08,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 08:49:13,172] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 08:49:13,479] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:11:49,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:11:50,184] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:28:36,270] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:28:36,617] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:38:35,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:38:35,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 09:47:46,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 09:47:47,144] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:12:25,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:12:26,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:34:15,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:34:16,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 10:47:44,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 10:47:44,612] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:09:32,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:09:33,050] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:23:19,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:23:19,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:33:38,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:33:39,198] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 11:47:56,501] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 11:47:56,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:20:03,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:20:03,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 12:55:20,700] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 12:55:21,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:18:50,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:18:50,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:38:16,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:38:16,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 13:47:48,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 13:47:48,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-11-01 14:10:30,730] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-11-01 14:10:31,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
