[2024-08-01 00:49:58,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 00:49:59,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
