[2024-08-01 00:49:58,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 00:49:59,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:06:52,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:06:52,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 02:46:31,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 02:46:31,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:11:29,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:11:30,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:28:31,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:28:31,358] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:37:38,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:37:38,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 03:47:57,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 03:47:58,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:12:12,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:12:12,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:29:26,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:29:26,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:39:00,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:39:01,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 04:47:46,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 04:47:46,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:09:59,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:09:59,830] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:27:49,134] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:27:49,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:36:18,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:36:19,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 05:47:38,336] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 05:47:38,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:14:08,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:14:08,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:33:57,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:33:57,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 06:47:38,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 06:47:38,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:09:41,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:09:42,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:22:07,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:22:07,616] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:33:27,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:33:28,129] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 07:47:57,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 07:47:57,606] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:12:59,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:12:59,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:30:34,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:30:35,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 08:47:52,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 08:47:52,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:09:49,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:09:49,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:25:09,777] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:25:10,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:33:19,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:33:20,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 09:47:44,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 09:47:45,128] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:11:30,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:11:31,096] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:30:34,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:30:35,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 10:47:31,561] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 10:47:31,989] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:09:11,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:09:11,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:22:30,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:22:30,481] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:33:22,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:33:23,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 11:47:59,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 11:48:00,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:18:07,997] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:18:08,302] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 12:51:46,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 12:51:46,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:14:00,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:14:00,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:27:58,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:27:58,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:35:18,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:35:19,244] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 13:47:42,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 13:47:42,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:09:28,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:09:28,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:27:39,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:27:39,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:36:45,032] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:36:45,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 14:47:40,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 14:47:40,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:10:11,167] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:10:11,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:26:01,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:26:01,777] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:33:43,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:33:44,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 15:47:58,234] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 15:47:58,659] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:12:04,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:12:05,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:32:05,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:32:05,441] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 16:47:47,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 16:47:47,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:10:30,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:10:30,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:28:12,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:28:12,641] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:35:25,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:35:25,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 17:47:52,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 17:47:53,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:12:41,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:12:41,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:31:49,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:31:49,673] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 18:47:35,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 18:47:35,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:07:42,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:07:42,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:19:24,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:19:24,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:32:59,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:33:00,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 19:47:45,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 19:47:45,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:11:24,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:11:24,738] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:26:09,764] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:26:10,150] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:35:51,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:35:51,882] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 20:47:39,634] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 20:47:40,065] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:10:33,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:10:33,899] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:25:30,207] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:25:30,581] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:33:25,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:33:26,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 21:47:53,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 21:47:53,505] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:08:55,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:08:55,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:27:15,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:27:15,762] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:35:49,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:35:49,716] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 22:47:31,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 22:47:32,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:09:37,567] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:09:38,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:24:58,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:24:58,565] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:33:30,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:33:31,218] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-01 23:48:01,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-01 23:48:01,677] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 00:44:25,992] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 00:44:26,322] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 01:50:52,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 01:50:53,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 02:30:21,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 02:30:21,742] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 02:49:03,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 02:49:03,763] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:11:14,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:11:14,809] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:28:55,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:28:55,904] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:38:19,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:38:19,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 03:47:49,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 03:47:49,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:12:07,140] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:12:07,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:31:31,545] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:31:31,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 04:47:26,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 04:47:26,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:09:39,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:09:39,710] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:28:25,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:28:25,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:37:12,147] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:37:12,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 05:47:36,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 05:47:36,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:15:23,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:15:23,620] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:35:40,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:35:40,513] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 06:48:45,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 06:48:45,456] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:10:49,790] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:10:50,151] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:23:11,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:23:12,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:33:16,900] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:33:17,393] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 07:47:27,569] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 07:47:27,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:12:37,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:12:37,917] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:31:14,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:31:14,991] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 08:47:49,167] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 08:47:49,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:11:00,935] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:11:01,161] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:26:36,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:26:36,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:34:18,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:34:18,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 09:47:55,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 09:47:56,152] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:10:22,078] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:10:22,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:29:44,288] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:29:44,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:39:03,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:39:03,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 10:47:38,644] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 10:47:38,937] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:08:36,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:08:37,084] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:21:09,444] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:21:09,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:33:05,390] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:33:05,820] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 11:47:53,862] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 11:47:54,283] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 12:17:26,726] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 12:17:26,952] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 12:50:59,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 12:50:59,756] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:12:58,599] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:12:58,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:27:03,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:27:03,427] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:34:44,439] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:34:44,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 13:47:56,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 13:47:56,775] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:09:23,331] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:09:23,619] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:27:02,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:27:03,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:35:47,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:35:47,710] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 14:47:29,489] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 14:47:29,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:09:59,374] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:09:59,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:25:48,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:25:48,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:33:30,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:33:30,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 15:47:46,056] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 15:47:46,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:11:55,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:11:55,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:33:03,605] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:33:03,923] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 16:47:40,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 16:47:40,540] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:09:14,582] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:09:15,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:26:03,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:26:03,406] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:33:34,232] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:33:34,576] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 17:47:51,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 17:47:52,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:13:24,633] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:13:25,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:32:19,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:32:19,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 18:47:46,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 18:47:46,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:07:34,583] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:07:34,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:20:19,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:20:19,688] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:34:05,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:34:06,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 19:47:40,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 19:47:41,122] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:10:58,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:10:58,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:26:07,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:26:08,264] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:33:36,422] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:33:36,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 20:47:33,256] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 20:47:33,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:09:57,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:09:57,839] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:23:32,829] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:23:33,273] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:33:19,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:33:19,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 21:47:50,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 21:47:50,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-08-02 22:10:02,973] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-08-02 22:10:03,277] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
