[2024-07-01 00:49:31,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 00:49:32,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:05:26,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:05:26,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:45:29,679] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:45:30,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:11:23,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:11:23,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:28:31,461] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:28:31,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:38:06,049] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:38:06,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:47:33,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:47:34,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:11:58,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:11:58,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:28:45,955] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:28:46,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:38:00,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:38:00,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:47:40,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:47:40,423] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:10:25,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:10:25,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:27:40,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:27:41,158] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:36:27,012] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:36:27,452] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:47:32,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:47:33,054] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:14:35,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:14:35,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:34:48,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:34:49,095] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:47:30,834] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:47:31,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:10:38,759] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:10:39,179] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:23:18,507] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:23:18,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:34:19,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:34:20,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:47:51,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:47:51,543] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:13:20,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:13:20,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:30:33,177] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:30:33,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:47:33,789] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:47:33,987] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:13:01,363] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:13:01,647] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:29:52,394] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:29:52,874] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:38:57,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:38:58,211] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:47:28,247] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:47:28,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:11:37,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:11:37,593] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:32:43,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:32:44,173] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:47:46,681] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:47:47,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:08:27,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:08:28,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:20:55,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:20:55,738] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:33:31,260] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:47:56,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:47:57,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 12:18:32,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 12:18:32,912] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 12:52:08,409] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 12:52:08,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:13:57,957] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:13:58,289] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:28:15,048] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:28:15,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:35:38,272] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:35:38,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:47:41,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:47:41,887] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:09:06,944] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:09:07,319] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:26:45,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:26:45,755] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:36:27,942] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:36:28,344] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:47:39,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:47:39,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:09:56,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:09:56,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:25:42,221] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:25:42,444] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:33:34,715] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:33:35,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:47:40,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:47:40,961] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:11:26,926] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:11:27,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:30:13,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:30:13,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:42:57,053] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:42:57,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:49:50,742] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:49:51,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:09:10,648] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:09:11,090] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:27:07,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:27:08,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:35:08,052] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:35:08,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:47:40,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:47:41,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:12:41,248] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:12:41,448] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:31:12,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:31:12,494] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:47:53,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:47:53,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:08:40,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:08:40,518] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:20:33,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:20:34,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:33:02,907] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:33:03,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:47:48,475] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:47:48,670] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:10:14,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:10:14,620] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:24:32,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:24:32,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:33:03,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:33:04,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:47:59,962] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:48:00,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:09:33,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:09:33,776] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:24:07,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:24:08,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:33:05,430] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:33:05,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:47:55,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:47:55,978] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:09:54,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:09:54,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:27:18,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:27:19,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:35:51,171] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:35:51,471] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:47:51,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:47:51,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:09:57,306] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:09:57,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:23:24,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:23:24,878] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
