[2025-07-01 01:09:38,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 01:09:38,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 03:09:13,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 03:09:14,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
