[2025-05-01 01:04:15,995] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 01:04:16,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 02:55:06,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 02:55:07,315] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 03:41:32,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 03:41:33,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:02:19,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:02:20,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:36:46,166] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:36:46,482] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:52:08,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:52:09,023] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:13:10,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:13:10,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:33:13,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:33:13,470] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:47:59,893] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:48:00,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:18:21,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:18:21,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:46:51,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:46:51,770] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:12:45,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:12:46,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:28:44,123] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:28:44,460] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:38:11,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:38:11,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:47:46,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:47:46,450] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:16:30,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:16:30,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:43:10,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:43:11,133] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:54:27,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:54:27,274] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:13:09,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:13:09,422] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:31:18,014] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:31:18,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:47:39,100] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:47:39,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:12:46,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:12:46,297] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:35:52,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:35:52,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:50:12,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:50:13,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:10:33,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:10:33,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:24:54,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:24:54,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:33:51,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:33:52,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:47:56,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:47:57,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 12:22:25,617] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 12:22:25,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:00:41,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:00:41,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:35:43,744] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:35:43,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:48:42,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:48:43,106] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:11:37,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:11:37,890] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:31:38,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:31:38,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:48:02,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:48:02,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:12:01,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:12:02,075] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:30:47,624] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:30:47,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:48:24,738] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:48:25,101] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:15:10,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:15:11,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:39:54,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:39:55,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:53:27,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:53:28,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:11:00,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:11:00,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:30:07,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:30:07,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
