[2025-06-01 01:12:55,278] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 01:12:55,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 03:12:55,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 03:12:56,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:06:06,225] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:06:06,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:47:08,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:47:08,622] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:12:52,776] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:12:53,195] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:33:27,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:33:27,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:48:26,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:48:27,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 06:17:16,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 06:17:16,451] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
