[2025-06-01 01:12:55,278] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 01:12:55,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 03:12:55,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 03:12:56,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:06:06,225] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:06:06,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
