[2025-08-01 01:14:22,571] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 01:14:22,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 03:24:15,348] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 03:24:15,689] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 04:35:54,899] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 04:35:55,285] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 05:18:43,837] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 05:18:43,994] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 05:52:25,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 05:52:26,078] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 06:22:32,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 06:22:32,913] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 06:56:06,938] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 06:56:07,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:21:13,602] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:21:13,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:44:37,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:44:37,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:54:46,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:54:46,607] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 08:18:50,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 08:18:51,131] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 08:50:42,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 08:50:42,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 09:18:49,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 09:18:49,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 09:46:50,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 09:46:50,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:14:57,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:14:58,141] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:43:21,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:43:21,453] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:56:43,722] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:56:43,991] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:14:25,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:14:25,428] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:31:04,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:31:05,223] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:49:39,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:49:39,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 12:27:00,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 12:27:01,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 13:11:24,368] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 13:11:24,749] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 13:49:39,998] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 13:49:40,246] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
