[2025-08-01 01:14:22,571] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 01:14:22,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 03:24:15,348] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 03:24:15,689] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 04:35:54,899] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 04:35:55,285] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 05:18:43,837] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 05:18:43,994] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 05:52:25,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 05:52:26,078] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 06:22:32,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 06:22:32,913] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 06:56:06,938] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 06:56:07,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:21:13,602] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:21:13,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:44:37,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:44:37,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 07:54:46,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 07:54:46,607] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 08:18:50,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 08:18:51,131] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 08:50:42,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 08:50:42,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 09:18:49,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 09:18:49,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 09:46:50,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 09:46:50,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:14:57,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:14:58,141] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:43:21,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:43:21,453] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 10:56:43,722] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 10:56:43,991] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:14:25,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:14:25,428] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:31:04,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:31:05,223] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 11:49:39,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 11:49:39,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 12:27:00,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 12:27:01,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 13:11:24,368] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 13:11:24,749] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 13:49:39,998] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 13:49:40,246] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 14:15:46,105] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 14:15:46,398] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 14:46:03,712] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 14:46:03,982] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 15:14:39,327] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 15:14:39,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 15:37:54,394] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 15:37:54,756] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 15:53:06,990] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 15:53:07,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 16:17:16,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 16:17:16,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 16:50:37,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 16:50:37,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 17:16:00,734] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 17:16:00,981] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 17:44:35,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 17:44:35,646] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 17:55:52,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 17:55:52,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 18:20:32,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 18:20:32,509] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 18:51:55,043] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 18:51:55,294] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 19:13:23,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 19:13:23,675] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 19:28:19,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 19:28:19,340] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 19:39:09,904] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 19:39:10,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 19:48:03,435] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 19:48:03,713] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 20:14:44,098] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 20:14:44,324] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 20:37:15,985] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 20:37:16,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 20:53:20,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 20:53:20,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 21:12:45,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 21:12:45,526] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 21:31:59,024] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 21:31:59,367] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 21:50:10,953] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 21:50:11,375] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 22:13:05,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 22:13:05,403] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 22:36:30,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 22:36:30,835] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 22:53:08,482] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 22:53:08,847] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 23:13:41,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 23:13:41,394] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 23:32:43,559] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 23:32:43,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-01 23:50:35,255] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-01 23:50:35,465] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 01:03:53,281] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 01:03:53,619] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 03:01:23,537] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 03:01:23,899] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 04:03:01,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 04:03:01,557] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 04:48:33,311] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 04:48:33,583] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 05:17:48,676] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 05:17:49,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 05:47:09,396] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 05:47:09,612] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 06:18:03,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 06:18:03,532] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 06:49:45,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 06:49:45,711] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 07:12:51,794] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 07:12:52,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 07:30:26,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 07:30:26,983] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 07:41:52,168] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 07:41:52,386] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 07:49:48,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 07:49:48,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 08:16:30,801] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 08:16:31,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 08:46:03,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 08:46:03,340] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 09:15:04,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 09:15:04,629] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 09:35:58,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 09:35:59,199] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 09:50:32,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 09:50:33,096] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 10:13:19,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 10:13:19,278] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 10:37:23,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 10:37:23,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 10:53:00,005] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 10:53:00,229] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 11:11:19,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 11:11:19,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 11:27:31,210] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 11:27:31,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 11:38:30,326] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 11:38:30,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 11:47:44,594] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 11:47:44,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 12:24:20,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 12:24:20,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 13:05:43,951] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 13:05:44,341] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 13:41:18,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 13:41:18,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 13:52:19,911] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 13:52:20,204] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 14:12:02,108] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 14:12:02,356] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 14:33:44,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 14:33:44,734] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 14:50:59,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 14:50:59,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 15:12:42,775] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 15:12:43,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 15:32:50,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 15:32:50,567] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 15:50:01,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 15:50:01,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 16:14:47,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 16:14:47,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 16:43:03,572] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 16:43:03,964] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 16:56:59,116] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 16:56:59,385] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 17:14:17,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 17:14:17,436] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 17:35:01,745] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 17:35:02,033] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 17:50:34,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 17:50:34,778] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 18:17:47,483] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 18:17:47,792] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 18:49:24,257] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 18:49:24,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 19:09:51,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 19:09:51,297] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 19:25:57,944] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 19:25:58,153] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 19:36:39,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 19:36:39,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 19:47:39,044] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 19:47:39,435] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 20:13:35,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 20:13:35,416] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 20:34:02,609] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 20:34:02,934] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 20:51:27,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 20:51:27,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 21:11:42,081] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 21:11:42,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 21:30:26,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 21:30:26,795] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 21:43:52,971] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 21:43:53,281] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 21:51:31,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 21:51:32,187] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 22:12:27,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 22:12:28,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 22:35:13,801] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 22:35:14,197] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 22:52:03,003] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 22:52:03,364] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 23:13:28,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 23:13:28,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 23:33:44,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 23:33:45,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-02 23:52:53,105] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-02 23:52:53,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 01:13:33,310] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 01:13:33,702] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 03:21:45,572] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 03:21:45,972] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 04:30:59,405] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 04:30:59,677] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 05:06:34,939] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 05:06:35,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 05:43:03,648] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 05:43:04,050] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 05:56:34,927] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 05:56:35,322] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 06:21:50,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 06:21:50,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 06:50:10,016] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 06:50:10,250] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 07:13:04,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 07:13:05,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 07:31:35,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 07:31:35,501] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 07:48:13,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 07:48:13,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 08:16:34,173] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 08:16:34,573] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 08:45:30,381] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 08:45:30,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 09:13:14,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 09:13:14,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 09:33:56,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 09:33:57,177] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 09:50:39,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 09:50:39,306] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 10:13:18,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 10:13:19,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 10:38:14,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 10:38:14,477] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 10:52:45,310] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 10:52:45,766] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 11:11:23,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 11:11:23,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 11:29:06,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 11:29:07,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 11:41:29,002] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 11:41:29,231] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 11:49:30,380] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 11:49:30,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 12:24:52,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 12:24:52,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 13:08:12,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 13:08:13,259] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 13:43:18,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 13:43:19,039] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 13:54:30,910] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 13:54:31,214] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 14:11:25,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 14:11:25,437] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 14:33:17,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 14:33:17,319] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 14:50:40,698] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 14:50:41,086] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 15:12:51,155] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 15:12:51,431] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 15:33:58,573] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 15:33:58,846] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 15:52:24,376] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 15:52:24,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 16:15:10,105] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 16:15:10,510] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 16:42:57,651] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 16:42:57,990] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-08-03 16:56:49,563] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-08-03 16:56:49,960] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
