[2025-05-01 01:04:15,995] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 01:04:16,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 02:55:06,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 02:55:07,315] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 03:41:32,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 03:41:33,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:02:19,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:02:20,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:36:46,166] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:36:46,482] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:52:08,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:52:09,023] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:13:10,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:13:10,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:33:13,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:33:13,470] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:47:59,893] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:48:00,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:18:21,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:18:21,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:46:51,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:46:51,770] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:12:45,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:12:46,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:28:44,123] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:28:44,460] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:38:11,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:38:11,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:47:46,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:47:46,450] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:16:30,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:16:30,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:43:10,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:43:11,133] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:54:27,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:54:27,274] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:13:09,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:13:09,422] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:31:18,014] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:31:18,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:47:39,100] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:47:39,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:12:46,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:12:46,297] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:35:52,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:35:52,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:50:12,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:50:13,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:10:33,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:10:33,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:24:54,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:24:54,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:33:51,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:33:52,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:47:56,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:47:57,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 12:22:25,617] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 12:22:25,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:00:41,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:00:41,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:35:43,744] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:35:43,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:48:42,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:48:43,106] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:11:37,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:11:37,890] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:31:38,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:31:38,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:48:02,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:48:02,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:12:01,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:12:02,075] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:30:47,624] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:30:47,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:48:24,738] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:48:25,101] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:15:10,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:15:11,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:39:54,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:39:55,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:53:27,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:53:28,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:11:00,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:11:00,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:30:07,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:30:07,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:41:22,634] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:41:23,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:48:33,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:48:33,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 18:17:00,722] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 18:17:01,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 18:45:51,388] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 18:45:51,737] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:09:31,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:09:32,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:23:30,410] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:23:30,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:33:58,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:33:59,072] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:47:41,631] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:47:42,025] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:12:39,699] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:12:40,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:30:33,511] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:30:33,850] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:47:42,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:47:42,432] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:11:47,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:11:48,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:27:07,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:27:07,574] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:36:04,911] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:36:05,313] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:47:43,961] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:47:44,219] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:11:41,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:11:42,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:32:47,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:32:47,634] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:48:00,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:48:00,448] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:11:54,391] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:11:54,754] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:28:19,741] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:28:20,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:38:43,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:38:44,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:47:44,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:47:44,918] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 00:58:56,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 00:58:56,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 02:38:12,216] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 02:38:12,456] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 03:30:10,825] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 03:30:11,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 03:53:29,753] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 03:53:30,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:14:56,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:14:57,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:36:59,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:36:59,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:52:20,802] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:52:21,137] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:12:56,519] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:12:56,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:33:15,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:33:15,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:47:55,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:47:55,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 06:17:30,454] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 06:17:30,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 06:46:21,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 06:46:22,007] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:12:25,813] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:12:26,177] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:28:49,335] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:28:49,693] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:38:28,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:38:28,601] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:47:38,361] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:47:38,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 08:16:10,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 08:16:10,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 08:43:43,140] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 08:43:43,518] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 08:54:40,836] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 08:54:41,216] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 09:12:50,144] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 09:12:50,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 09:30:51,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 09:30:52,152] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 09:47:34,133] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 09:47:34,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 10:12:58,390] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 10:12:58,735] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 10:35:19,383] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 10:35:19,671] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 10:49:51,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 10:49:52,231] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 11:10:19,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 11:10:19,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 11:25:34,817] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 11:25:35,159] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 11:33:57,804] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 11:33:58,093] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 11:47:32,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 11:47:32,502] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 12:22:53,371] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 12:22:53,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 13:01:14,821] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 13:01:15,025] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 13:36:27,528] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 13:36:27,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 13:48:46,927] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 13:48:47,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 14:12:02,874] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 14:12:03,173] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 14:33:04,671] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 14:33:04,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 14:48:48,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 14:48:48,414] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 15:12:36,992] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 15:12:37,372] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 15:31:19,276] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 15:31:19,636] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 15:47:40,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 15:47:40,999] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 16:14:37,235] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 16:14:37,501] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 16:40:10,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 16:40:11,230] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 16:52:55,530] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 16:52:55,886] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 17:11:06,327] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 17:11:06,594] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 17:29:51,609] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 17:29:51,950] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 17:41:11,725] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 17:41:12,003] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 17:48:24,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 17:48:24,703] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 18:16:28,070] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 18:16:28,378] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 18:44:39,995] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 18:44:40,334] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 18:53:37,717] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 18:53:38,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 19:10:15,836] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 19:10:16,169] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 19:24:06,987] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 19:24:07,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 19:34:04,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 19:34:04,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 19:47:50,034] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 19:47:50,383] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 20:13:45,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 20:13:46,148] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 20:32:10,571] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 20:32:10,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 20:48:02,858] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 20:48:03,264] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 21:11:02,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 21:11:03,028] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 21:27:48,664] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 21:27:48,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 21:38:15,612] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 21:38:15,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 21:47:39,996] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 21:47:40,251] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 22:11:41,049] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 22:11:41,261] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 22:32:36,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 22:32:36,903] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 22:49:21,467] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 22:49:22,011] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 23:11:32,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 23:11:32,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 23:27:54,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 23:27:54,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 23:37:45,648] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 23:37:46,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 23:47:41,449] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 23:47:41,795] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 00:57:26,277] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 00:57:26,636] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 02:26:13,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 02:26:13,460] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 03:23:32,952] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 03:23:33,316] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 03:48:41,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 03:48:41,948] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 04:14:08,255] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 04:14:08,557] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 04:35:16,059] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 04:35:16,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 04:50:56,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 04:50:56,836] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 05:11:46,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 05:11:46,629] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 05:32:10,863] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 05:32:11,248] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 05:47:38,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 05:47:38,649] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 06:15:37,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 06:15:37,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 06:43:37,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 06:43:37,972] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 06:52:39,319] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 06:52:39,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 07:10:53,667] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 07:10:53,984] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 07:26:08,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 07:26:09,193] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 07:35:34,523] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 07:35:34,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 07:47:47,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 07:47:47,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 08:14:11,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 08:14:12,116] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 08:34:15,074] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 08:34:15,371] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 08:50:29,745] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 08:50:30,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 09:11:42,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 09:11:42,599] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 09:28:15,040] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 09:28:15,394] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 09:38:11,544] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 09:38:11,911] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 09:48:02,395] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 09:48:02,669] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 10:11:30,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 10:11:30,861] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 10:32:49,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 10:32:50,131] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 10:47:42,689] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 10:47:43,074] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 11:09:17,333] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 11:09:17,693] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 11:23:51,768] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 11:23:52,124] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 11:33:49,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 11:33:49,770] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 11:47:42,642] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 11:47:43,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 12:20:52,074] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 12:20:52,505] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 12:57:55,257] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 12:57:55,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 13:22:54,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 13:22:55,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 13:38:45,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 13:38:46,204] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 13:47:42,383] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 13:47:42,627] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 14:10:42,077] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 14:10:42,450] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 14:29:35,405] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 14:29:35,734] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 14:40:29,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 14:40:29,830] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 14:47:44,188] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 14:47:44,610] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 15:11:03,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 15:11:03,370] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 15:28:19,164] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 15:28:19,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 15:38:13,889] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 15:38:14,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 15:47:53,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 15:47:53,617] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 16:13:23,022] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 16:13:23,395] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 16:35:16,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 16:35:17,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 16:50:32,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 16:50:32,351] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 17:09:42,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 17:09:43,062] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 17:27:42,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 17:27:43,134] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 17:37:39,497] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 17:37:39,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 17:47:34,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 17:47:34,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 18:15:06,610] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 18:15:06,994] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 18:38:11,551] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 18:38:11,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 18:50:32,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 18:50:33,104] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 19:09:05,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 19:09:05,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 19:22:19,283] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 19:22:19,670] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 19:33:55,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 19:33:56,202] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 19:47:42,042] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 19:47:42,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 20:12:35,530] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 20:12:35,828] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 20:29:50,170] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 20:29:50,542] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 20:40:25,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 20:40:25,804] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 20:47:36,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 20:47:36,528] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 21:10:22,977] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 21:10:23,374] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 21:26:24,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 21:26:24,432] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 21:35:08,441] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 21:35:08,857] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 21:47:55,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 21:47:55,620] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 22:10:45,953] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 22:10:46,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 22:30:57,111] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 22:30:57,427] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 22:47:40,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 22:47:41,262] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 23:11:14,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 23:11:15,005] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 23:27:14,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 23:27:14,796] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 23:36:44,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 23:36:44,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-03 23:47:31,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-03 23:47:32,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 01:04:33,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 01:04:34,202] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 02:54:35,419] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 02:54:35,771] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 03:40:09,288] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 03:40:09,502] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 04:00:55,111] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 04:00:55,473] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 04:34:40,432] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 04:34:40,794] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 04:50:43,084] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 04:50:43,465] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 05:12:11,357] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 05:12:11,731] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 05:31:55,614] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 05:31:55,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 05:47:48,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 05:47:48,921] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 06:16:36,694] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 06:16:37,114] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 06:44:29,938] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 06:44:30,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 06:53:58,794] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 06:53:58,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 07:11:06,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 07:11:06,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 07:26:19,480] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 07:26:19,859] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 07:34:24,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 07:34:24,382] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 07:47:41,232] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 07:47:41,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 08:14:20,996] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 08:14:21,336] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 08:34:26,289] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 08:34:26,570] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 08:50:13,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 08:50:13,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 09:12:04,918] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 09:12:05,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 09:28:41,039] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 09:28:41,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 09:38:10,437] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 09:38:10,713] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 09:47:36,395] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 09:47:36,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 10:11:45,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 10:11:45,995] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 10:33:03,202] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 10:33:03,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-04 10:47:40,869] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-04 10:47:41,236] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
