[2025-07-01 01:09:38,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 01:09:38,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 03:09:13,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 03:09:14,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:06:44,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:06:44,973] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:49:04,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:49:04,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:17:35,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:17:36,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:44:16,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:44:16,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:53:44,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:53:45,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:19:42,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:19:43,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:50:45,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:50:45,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:14:32,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:14:33,047] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:33:31,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:50:52,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:50:52,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:18:01,082] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:18:01,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:48:13,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:48:13,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:15:40,982] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:15:41,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:42:18,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:42:18,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:52:28,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:52:28,878] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:14:30,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:14:30,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:40:39,010] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:40:39,323] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:53:34,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:53:34,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:11:23,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:11:23,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:27:58,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:27:58,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:38:56,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:38:56,503] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:47:54,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:47:55,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 12:25:50,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 12:25:50,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:07:09,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:07:09,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:43:51,309] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:43:51,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:55:12,428] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:55:12,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:12:23,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:12:24,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:33:27,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:33:27,318] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:51:11,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:51:11,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:13:49,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:13:49,485] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:34:12,870] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:34:13,171] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:50:39,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:50:40,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 16:16:36,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 16:16:37,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 16:48:29,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 16:48:29,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:12:08,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:12:08,929] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:34:20,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:34:20,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:51:14,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:51:14,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 18:17:39,630] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 18:17:39,869] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 18:47:32,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 18:47:32,626] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:10:17,896] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:10:18,190] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:25:15,057] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:25:15,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:35:19,137] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:35:19,346] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:47:59,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:47:59,882] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:14:07,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:14:07,819] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:34:06,127] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:34:06,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:51:01,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:51:01,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:11:45,482] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:11:45,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:29:54,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:29:54,513] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:41:54,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:41:55,267] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:50:52,524] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:50:52,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:12:14,920] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:12:15,145] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:34:11,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:34:12,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:50:37,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:50:37,476] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:12:18,164] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:12:18,496] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:29:59,761] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:30:00,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:42:01,442] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:42:01,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:49:54,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:49:54,637] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 01:02:34,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 01:02:34,744] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 02:56:04,877] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 02:56:05,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 03:47:39,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 03:47:40,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 04:23:18,582] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 04:23:18,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 04:49:02,829] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 04:49:03,237] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:15:16,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:15:17,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:40:25,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:40:25,958] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:52:19,286] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:52:19,613] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 06:19:44,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 06:19:44,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 06:50:00,814] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 06:50:01,200] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:13:28,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:13:29,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:31:20,809] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:31:21,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:48:32,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:48:32,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 08:17:58,229] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 08:17:58,577] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 08:47:52,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 08:47:52,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:15:30,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:15:31,124] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:42:32,256] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:42:32,635] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:52:28,257] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:52:28,593] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:14:16,926] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:14:17,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:40:11,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:40:11,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:53:18,437] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:53:18,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:11:46,266] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:11:46,642] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:28:10,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:28:10,446] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:38:57,493] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:38:57,863] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:48:02,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:48:02,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 12:25:01,819] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 12:25:02,061] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:06:45,198] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:06:45,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:43:11,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:43:11,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:54:00,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:54:00,723] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:13:01,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:13:02,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:35:26,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:35:27,134] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:52:12,942] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:52:13,188] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:13:44,945] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:13:45,252] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:34:34,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:34:35,167] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:51:35,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:51:35,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 16:15:36,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 16:15:37,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 16:47:49,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 16:47:49,475] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 17:12:39,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 17:12:39,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
