[2025-07-01 01:09:38,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 01:09:38,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 03:09:13,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 03:09:14,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:06:44,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:06:44,973] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:49:04,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:49:04,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:17:35,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:17:36,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:44:16,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:44:16,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:53:44,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:53:45,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:19:42,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:19:43,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:50:45,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:50:45,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:14:32,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:14:33,047] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:33:31,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:50:52,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:50:52,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:18:01,082] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:18:01,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:48:13,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:48:13,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:15:40,982] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:15:41,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:42:18,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:42:18,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:52:28,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:52:28,878] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:14:30,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:14:30,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:40:39,010] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:40:39,323] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:53:34,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:53:34,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:11:23,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:11:23,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:27:58,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:27:58,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:38:56,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:38:56,503] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:47:54,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:47:55,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 12:25:50,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 12:25:50,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:07:09,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:07:09,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:43:51,309] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:43:51,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:55:12,428] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:55:12,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:12:23,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:12:24,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:33:27,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:33:27,318] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:51:11,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:51:11,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:13:49,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:13:49,485] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:34:12,870] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:34:13,171] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
