[2025-06-01 01:12:55,278] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 01:12:55,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 03:12:55,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 03:12:56,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:06:06,225] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:06:06,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:47:08,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:47:08,622] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:12:52,776] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:12:53,195] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:33:27,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:33:27,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:48:26,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:48:27,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 06:17:16,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 06:17:16,451] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 06:46:42,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 06:46:42,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:11:47,395] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:11:47,774] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:28:09,080] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:28:09,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:38:22,023] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:38:22,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:47:33,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:47:33,691] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:15:24,282] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:15:24,701] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:38:33,551] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:38:33,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:53:42,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:53:42,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:12:20,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:12:20,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:29:55,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:29:55,917] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:40:54,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:40:54,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:48:05,238] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:48:05,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:12:30,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:12:30,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:35:07,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:35:07,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:49:15,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:49:15,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:09:43,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:09:43,711] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:24:39,025] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:24:39,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:33:50,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:33:50,896] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:47:49,244] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:47:49,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 12:22:01,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 12:22:01,950] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:00:45,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:00:46,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:35:21,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:35:21,529] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:48:00,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:48:00,897] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:10:50,427] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:10:50,798] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:30:33,659] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:30:34,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:44:03,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:44:03,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:51:15,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:51:15,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:11:16,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:11:17,352] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:29:21,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:29:22,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:40:01,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:40:01,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:47:52,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:47:52,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:13:49,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:13:49,914] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:38:18,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:38:19,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:52:53,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:52:53,695] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:10:18,701] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:10:19,093] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:29:08,930] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:29:09,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:40:41,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:40:42,099] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:48:03,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:48:04,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:15:39,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:15:40,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:44:07,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:44:07,633] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:53:14,708] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:53:15,104] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:09:23,074] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:09:23,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:23:31,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:23:31,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:34:23,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:34:23,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:47:45,666] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:47:46,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:13:03,432] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:13:03,796] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:31:50,606] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:31:50,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:48:29,755] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:48:30,136] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:10:45,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:10:46,335] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:27:24,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:27:24,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:37:01,659] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:37:02,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:47:58,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:47:59,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 22:11:44,592] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 22:11:44,971] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
