[2025-07-01 01:09:38,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 01:09:38,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 03:09:13,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 03:09:14,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:06:44,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:06:44,973] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:49:04,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:49:04,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:17:35,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:17:36,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:44:16,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:44:16,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:53:44,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:53:45,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:19:42,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:19:43,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:50:45,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:50:45,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:14:32,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:14:33,047] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:33:31,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:50:52,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:50:52,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
