[2025-06-01 01:12:55,278] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 01:12:55,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 03:12:55,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 03:12:56,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:06:06,225] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:06:06,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 04:47:08,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 04:47:08,622] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:12:52,776] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:12:53,195] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:33:27,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:33:27,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 05:48:26,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 05:48:27,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 06:17:16,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 06:17:16,451] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 06:46:42,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 06:46:42,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:11:47,395] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:11:47,774] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:28:09,080] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:28:09,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:38:22,023] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:38:22,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 07:47:33,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 07:47:33,691] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:15:24,282] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:15:24,701] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:38:33,551] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:38:33,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 08:53:42,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 08:53:42,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:12:20,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:12:20,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:29:55,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:29:55,917] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:40:54,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:40:54,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 09:48:05,238] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 09:48:05,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:12:30,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:12:30,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:35:07,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:35:07,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 10:49:15,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 10:49:15,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:09:43,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:09:43,711] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:24:39,025] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:24:39,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:33:50,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:33:50,896] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 11:47:49,244] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 11:47:49,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 12:22:01,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 12:22:01,950] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:00:45,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:00:46,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:35:21,146] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:35:21,529] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 13:48:00,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 13:48:00,897] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:10:50,427] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:10:50,798] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:30:33,659] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:30:34,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:44:03,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:44:03,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 14:51:15,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 14:51:15,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:11:16,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:11:17,352] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:29:21,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:29:22,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:40:01,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:40:01,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 15:47:52,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 15:47:52,497] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:13:49,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:13:49,914] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:38:18,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:38:19,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 16:52:53,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 16:52:53,695] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:10:18,701] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:10:19,093] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:29:08,930] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:29:09,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:40:41,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:40:42,099] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 17:48:03,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 17:48:04,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:15:39,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:15:40,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:44:07,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:44:07,633] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 18:53:14,708] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 18:53:15,104] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:09:23,074] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:09:23,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:23:31,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:23:31,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:34:23,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:34:23,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 19:47:45,666] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 19:47:46,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:13:03,432] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:13:03,796] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:31:50,606] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:31:50,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 20:48:29,755] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 20:48:30,136] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:10:45,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:10:46,335] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:27:24,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:27:24,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:37:01,659] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:37:02,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 21:47:58,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 21:47:59,127] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 22:11:44,592] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 22:11:44,971] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 22:32:42,570] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 22:32:42,846] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 22:48:28,982] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 22:48:29,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 23:11:42,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 23:11:42,676] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 23:28:41,292] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 23:28:41,633] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 23:39:09,019] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 23:39:09,366] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-01 23:47:46,362] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-01 23:47:46,718] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 01:03:30,124] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 01:03:30,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 02:58:18,466] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 02:58:18,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 03:50:51,460] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 03:50:51,763] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 04:23:44,578] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 04:23:44,927] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 04:49:56,392] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 04:49:56,767] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 05:14:16,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 05:14:16,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 05:36:13,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 05:36:13,857] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 05:50:35,399] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 05:50:35,756] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 06:19:41,619] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 06:19:41,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 06:49:58,974] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 06:49:59,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 07:13:44,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 07:13:44,356] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 07:31:40,289] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 07:31:40,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 07:47:49,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 07:47:49,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 08:18:46,718] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 08:18:47,084] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 08:46:57,545] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 08:46:57,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 09:14:50,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 09:14:51,314] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 09:34:26,198] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 09:34:26,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 09:49:33,645] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 09:49:33,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 10:14:16,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 10:14:17,706] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 10:39:35,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 10:39:35,760] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 10:52:00,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 10:52:00,760] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 11:11:26,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 11:11:26,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 11:27:23,882] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 11:27:24,263] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 11:37:12,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 11:37:13,217] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 11:47:45,552] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 11:47:45,727] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 12:25:12,835] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 12:25:13,078] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 13:06:01,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 13:06:02,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 13:42:53,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 13:42:53,431] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 13:53:31,727] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 13:53:31,988] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 14:13:29,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 14:13:29,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 14:36:46,439] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 14:36:46,791] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 14:52:04,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 14:52:04,652] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 15:14:00,179] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 15:14:00,517] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 15:34:37,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 15:34:37,943] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 15:50:49,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 15:50:49,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 16:16:05,752] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 16:16:06,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 16:49:03,313] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 16:49:03,491] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 17:11:57,764] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 17:11:58,116] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 17:32:08,836] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 17:32:09,017] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 17:48:41,079] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 17:48:41,431] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 18:17:30,108] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 18:17:30,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 18:47:42,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 18:47:43,154] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 19:09:56,527] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 19:09:56,776] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 19:24:44,565] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 19:24:44,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 19:34:06,380] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 19:34:06,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 19:47:43,306] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 19:47:43,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 20:14:08,184] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 20:14:08,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 20:33:42,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 20:33:42,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 20:49:50,357] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 20:49:50,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 21:12:31,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 21:12:31,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 21:32:13,014] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 21:32:13,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 21:47:55,266] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 21:47:55,662] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 22:12:20,962] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 22:12:22,057] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 22:33:37,996] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 22:33:38,415] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 22:49:04,594] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 22:49:04,813] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 23:11:48,242] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 23:11:48,449] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 23:31:15,608] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 23:31:15,903] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-02 23:48:52,717] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-02 23:48:53,081] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 01:01:56,490] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 01:01:56,755] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 02:53:53,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 02:53:53,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 03:42:11,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 03:42:12,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 04:03:39,467] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 04:03:39,886] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 04:39:29,124] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 04:39:29,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 04:53:21,412] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 04:53:21,775] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 05:13:48,836] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 05:13:49,256] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 05:34:38,759] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 05:34:39,140] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 05:49:43,800] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 05:49:44,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 06:18:49,587] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 06:18:49,966] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 06:50:13,255] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 06:50:13,642] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 07:13:25,093] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 07:13:25,488] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 07:31:54,447] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 07:31:54,820] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 07:47:53,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 07:47:54,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 08:18:22,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 08:18:23,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 08:47:31,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 08:47:32,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 09:14:15,709] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 09:14:16,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 09:34:31,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 09:34:31,757] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 09:50:19,557] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 09:50:19,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 10:14:09,806] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 10:14:10,227] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 10:39:47,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 10:39:47,765] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 10:52:24,682] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 10:52:25,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 11:11:14,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 11:11:15,076] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 11:27:22,691] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 11:27:23,001] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 11:37:39,954] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 11:37:40,231] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 11:48:00,989] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 11:48:01,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 12:25:12,980] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 12:25:13,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 13:06:51,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 13:06:51,483] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 13:44:09,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 13:44:09,228] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 13:55:15,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 13:55:15,473] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 14:13:28,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 14:13:28,294] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 14:37:41,381] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 14:37:41,765] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 14:53:52,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 14:53:52,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 15:14:23,469] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 15:14:23,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 15:35:24,412] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 15:35:24,794] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 15:51:46,563] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 15:51:46,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 16:16:49,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 16:16:49,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 16:49:19,024] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 16:49:19,387] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 17:12:14,024] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 17:12:14,402] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 17:33:04,038] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 17:33:04,293] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 17:48:45,213] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 17:48:45,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 18:18:03,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 18:18:03,728] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 18:48:28,373] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 18:48:28,733] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 19:09:49,283] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 19:09:49,636] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 19:24:53,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 19:24:54,240] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 19:34:04,212] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 19:34:04,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 19:47:56,190] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 19:47:56,599] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 20:14:30,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 20:14:31,412] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 20:34:39,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 20:34:40,163] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 20:48:58,749] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 20:48:59,077] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 21:11:23,984] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 21:11:24,348] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 21:27:53,390] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 21:27:53,702] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 21:38:18,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 21:38:18,943] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 21:47:49,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 21:47:49,552] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 22:12:40,084] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 22:12:40,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 22:34:25,806] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 22:34:26,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 22:49:33,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 22:49:33,788] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 23:11:43,353] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 23:11:43,705] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 23:29:18,793] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 23:29:19,081] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 23:40:19,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 23:40:19,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-03 23:47:34,193] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-03 23:47:34,445] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 01:01:30,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 01:01:30,330] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 02:54:03,386] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 02:54:03,761] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 03:42:32,820] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 03:42:33,203] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 04:03:25,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 04:03:26,030] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 04:40:02,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 04:40:02,872] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 04:53:44,603] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 04:53:44,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 05:13:21,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 05:13:22,336] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 05:34:29,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 05:34:30,280] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 05:50:18,867] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 05:50:19,246] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 06:18:32,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 06:18:32,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 06:48:34,615] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 06:48:34,841] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 07:13:04,462] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 07:13:04,840] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 07:30:39,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 07:30:40,175] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 07:47:36,199] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 07:47:36,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 08:17:48,197] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 08:17:48,528] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 08:47:10,107] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 08:47:10,467] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 09:13:37,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 09:13:38,340] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 09:34:10,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 09:34:11,090] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 09:49:41,207] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 09:49:41,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 10:13:56,027] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 10:13:56,427] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 10:38:52,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 10:38:53,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 10:52:16,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 10:52:16,591] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 11:11:20,111] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 11:11:20,380] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 11:28:14,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 11:28:14,927] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 11:39:23,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 11:39:23,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 11:47:41,829] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 11:47:42,252] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 12:25:13,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 12:25:14,017] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 13:07:13,430] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 13:07:13,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 13:45:21,741] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 13:45:22,001] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 13:55:15,279] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 13:55:15,521] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 14:10:45,133] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 14:10:45,309] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 14:46:31,535] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 14:46:31,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 15:37:13,261] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 15:37:13,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 16:00:16,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 16:00:16,755] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 16:25:53,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 16:25:53,491] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 16:44:45,360] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 16:44:45,573] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 16:55:30,994] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 16:55:31,305] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 17:11:44,292] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 17:11:44,631] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 17:32:48,718] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 17:32:49,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 17:48:44,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 17:48:45,277] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 18:17:35,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 18:17:35,607] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 18:47:38,050] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 18:47:38,323] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 19:10:33,587] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 19:10:33,983] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 19:24:30,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 19:24:31,198] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 19:33:14,105] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 19:33:14,460] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 19:47:42,458] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 19:47:42,817] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 20:11:15,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 20:11:16,004] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 20:27:11,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 20:27:11,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 20:35:48,809] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 20:35:49,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 20:47:56,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 20:47:56,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 21:10:14,404] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 21:10:14,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 21:24:18,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 21:24:18,964] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 21:33:22,194] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 21:33:22,418] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 21:47:37,498] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 21:47:37,743] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 22:11:40,179] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 22:11:40,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 22:29:49,285] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 22:29:49,480] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 22:40:01,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 22:40:01,588] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 22:47:32,818] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 22:47:33,154] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 23:12:02,581] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 23:12:02,963] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 23:29:38,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 23:29:38,451] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 23:40:55,500] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 23:40:55,881] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-04 23:47:58,282] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-04 23:47:58,626] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 01:00:57,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 01:00:58,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 02:53:21,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 02:53:22,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 03:43:12,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 03:43:13,201] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 04:04:29,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 04:04:30,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 04:40:46,689] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 04:40:47,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 04:54:23,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 04:54:23,961] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 05:13:41,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 05:13:41,505] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 05:35:29,664] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 05:35:29,986] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 05:50:31,202] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 05:50:31,393] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 06:18:57,419] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 06:18:57,748] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 06:50:07,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 06:50:07,506] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 07:12:58,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 07:12:58,828] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 07:30:22,968] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 07:30:23,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 07:41:05,733] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 07:41:06,107] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 07:48:19,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 07:48:23,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 08:17:19,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 08:17:19,391] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 08:45:45,996] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 08:45:46,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 09:13:44,432] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 09:13:44,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 09:33:31,353] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 09:33:31,532] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 09:49:35,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 09:49:35,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 10:14:15,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 10:14:15,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 10:40:51,730] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 10:40:52,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 10:52:59,072] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 10:52:59,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 11:11:18,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 11:11:18,640] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 11:27:29,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 11:27:30,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 11:37:57,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 11:37:57,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 11:47:42,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 11:47:42,875] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 12:25:12,145] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 12:25:12,524] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 13:05:50,903] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 13:05:51,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 13:43:26,765] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 13:43:27,089] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 13:54:42,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 13:54:42,547] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 14:12:44,120] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 14:12:44,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 14:35:34,477] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 14:35:34,658] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 14:51:03,307] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 14:51:03,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 15:13:34,903] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 15:13:35,270] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 15:33:49,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 15:33:49,575] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 15:51:00,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 15:51:00,922] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 16:15:59,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 16:15:59,793] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 16:45:57,695] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 16:45:57,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 17:09:25,619] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 17:09:26,004] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 17:26:14,802] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 17:26:15,179] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 17:35:10,859] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 17:35:11,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 17:47:50,742] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 17:47:51,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 18:59:03,483] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 18:59:03,729] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 19:09:38,873] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 19:09:39,319] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 19:21:52,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 19:21:52,507] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 19:33:25,827] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 19:33:26,159] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 19:47:42,102] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 19:47:42,506] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 20:11:53,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 20:11:54,012] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 20:27:42,155] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 20:27:42,495] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 20:36:09,324] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 20:36:09,654] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 20:48:08,253] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 20:48:08,642] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 21:11:41,833] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 21:11:42,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 21:29:28,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 21:29:28,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 21:40:04,159] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 21:40:04,558] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 21:47:32,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 21:47:32,788] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 22:11:01,955] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 22:11:02,295] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 22:32:27,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 22:32:28,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 22:48:32,914] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 22:48:33,310] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 23:13:45,402] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 23:13:45,782] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 23:31:59,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 23:32:00,156] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-05 23:48:57,024] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-05 23:48:57,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 01:00:54,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 01:00:54,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 02:52:38,525] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 02:52:38,901] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 03:42:18,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 03:42:18,554] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 04:02:57,858] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 04:02:58,245] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 04:40:09,155] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 04:40:09,485] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 04:53:39,483] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 04:53:39,845] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 05:13:16,040] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 05:13:16,316] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 05:36:06,854] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 05:36:07,199] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 05:51:52,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 05:51:52,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 06:18:58,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 06:18:58,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 06:50:16,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 06:50:16,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 07:12:21,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 07:12:22,208] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 07:29:22,786] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 07:29:23,116] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 07:40:03,268] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 07:40:03,687] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 07:47:50,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 07:47:50,998] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 08:17:17,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 08:17:17,560] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 08:45:04,648] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 08:45:05,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 08:56:36,261] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 08:56:36,682] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 09:16:12,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 09:16:12,944] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 09:39:40,933] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 09:39:41,259] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 09:49:11,401] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 09:49:11,793] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 10:14:10,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 10:14:10,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 10:39:38,642] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 10:39:39,023] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 10:52:06,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 10:52:06,376] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 11:11:16,127] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 11:11:16,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 11:27:08,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 11:27:08,443] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 11:37:18,077] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 11:37:18,398] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 11:47:44,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 11:47:45,114] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 12:24:05,224] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 12:24:05,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 13:04:04,296] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 13:04:04,638] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 13:41:47,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 13:41:48,667] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 13:52:55,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 13:52:56,140] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 14:12:32,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 14:12:32,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 14:33:58,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 14:33:58,380] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 14:49:10,719] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 14:49:11,002] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 15:11:08,558] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 15:11:08,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 15:30:28,118] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 15:30:28,341] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 15:43:50,405] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 15:43:50,711] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 15:50:24,226] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 15:50:24,588] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 16:16:06,088] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 16:16:06,308] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 16:46:46,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 16:46:46,707] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 17:11:44,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 17:11:44,430] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 17:32:35,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 17:32:35,444] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 17:48:29,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 17:48:29,466] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 18:17:50,026] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 18:17:50,403] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 18:47:22,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 18:47:22,671] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 19:10:08,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 19:10:08,534] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 19:25:06,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 19:25:06,932] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 19:33:52,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 19:33:53,354] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 19:47:41,677] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 19:47:41,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 20:14:32,272] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 20:14:32,652] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 20:33:54,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 20:33:54,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 20:50:15,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 20:50:16,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 21:11:33,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 21:11:33,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 21:29:04,445] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 21:29:04,829] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 21:39:40,801] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 21:39:41,138] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 21:47:51,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 21:47:51,372] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 22:11:50,936] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 22:11:51,293] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 22:33:45,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 22:33:46,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 22:47:39,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 22:47:40,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 23:12:16,181] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 23:12:16,561] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 23:29:26,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 23:29:26,555] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 23:40:18,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 23:40:18,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-06 23:47:31,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-06 23:47:31,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 01:00:21,250] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 01:00:21,613] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 02:43:59,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 02:44:00,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 03:35:11,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 03:35:12,328] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 03:59:44,441] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 03:59:44,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 04:26:51,673] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 04:26:52,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 04:43:52,377] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 04:43:52,734] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 04:54:58,335] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 04:54:58,585] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 05:12:11,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 05:12:11,783] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 05:32:03,173] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 05:32:03,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 05:47:55,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 05:47:56,206] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 06:16:21,819] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 06:16:22,153] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 06:45:28,038] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 06:45:28,414] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 06:54:55,432] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 06:54:55,983] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 07:11:19,634] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 07:11:19,952] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 07:27:03,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 07:27:03,686] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 07:35:51,778] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 07:35:52,157] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 07:47:53,569] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 07:47:53,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 08:14:42,733] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 08:14:43,218] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 08:35:41,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 08:35:42,236] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 08:51:45,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 08:51:45,866] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 09:12:05,004] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 09:12:05,277] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 09:29:18,383] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 09:29:18,746] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 09:39:36,673] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 09:39:37,037] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 09:47:42,588] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 09:47:42,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 10:12:13,291] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 10:12:13,438] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 10:34:55,752] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 10:34:56,090] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 10:50:43,531] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 10:50:43,942] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 11:09:38,512] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 11:09:38,852] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 11:24:12,885] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 11:24:13,165] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 11:35:26,121] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 11:35:26,526] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 11:47:48,338] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 11:47:48,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 12:21:36,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 12:21:37,305] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 13:00:08,073] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 13:00:08,339] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 13:29:25,325] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 13:29:25,654] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 13:42:48,847] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 13:42:49,229] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 13:50:02,137] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 13:50:02,392] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 14:10:40,782] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 14:10:41,206] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 14:30:13,115] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 14:30:13,432] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 14:42:03,744] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 14:42:04,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 14:49:25,000] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 14:49:25,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 15:11:32,366] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 15:11:32,639] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 15:29:31,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 15:29:31,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 15:41:17,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 15:41:17,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 15:48:27,331] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 15:48:27,705] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 16:13:42,211] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 16:13:42,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 16:37:27,436] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 16:37:27,769] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 16:53:43,751] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 16:53:44,126] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 17:10:15,724] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 17:10:16,142] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 17:28:44,085] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 17:28:44,446] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 17:39:22,656] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 17:39:23,099] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 17:47:44,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 17:47:44,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 18:15:41,145] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 18:15:41,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 18:44:09,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 18:44:10,148] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 18:53:37,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 18:53:37,948] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 19:09:11,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 19:09:11,369] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 19:23:10,127] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 19:23:10,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 19:33:51,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 19:33:51,695] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 19:47:39,009] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 19:47:39,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 20:12:40,455] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 20:12:40,904] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 20:30:54,679] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 20:30:54,969] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 20:47:48,464] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 20:47:48,795] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 21:10:36,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 21:10:36,760] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 21:27:05,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 21:27:05,387] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 21:36:27,191] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 21:36:27,514] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 21:47:50,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 21:47:50,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 22:11:05,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 22:11:06,089] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 22:31:59,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 22:31:59,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 22:48:00,346] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 22:48:02,176] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 23:11:58,678] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 23:11:58,914] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-06-07 23:29:42,650] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-06-07 23:29:42,898] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
