[2025-07-01 01:09:38,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 01:09:38,592] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 03:09:13,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 03:09:14,058] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:06:44,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:06:44,973] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 04:49:04,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 04:49:04,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:17:35,713] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:17:36,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:44:16,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:44:16,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 05:53:44,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 05:53:45,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:19:42,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:19:43,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 06:50:45,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 06:50:45,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:14:32,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:14:33,047] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:33:31,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 07:50:52,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 07:50:52,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:18:01,082] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:18:01,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 08:48:13,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 08:48:13,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:15:40,982] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:15:41,238] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:42:18,542] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:42:18,877] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 09:52:28,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 09:52:28,878] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:14:30,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:14:30,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:40:39,010] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:40:39,323] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 10:53:34,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 10:53:34,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:11:23,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:11:23,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:27:58,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:27:58,628] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:38:56,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:38:56,503] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 11:47:54,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 11:47:55,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 12:25:50,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 12:25:50,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:07:09,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:07:09,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:43:51,309] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:43:51,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 13:55:12,428] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 13:55:12,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:12:23,830] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:12:24,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:33:27,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:33:27,318] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 14:51:11,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 14:51:11,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:13:49,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:13:49,485] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:34:12,870] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:34:13,171] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 15:50:39,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 15:50:40,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 16:16:36,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 16:16:37,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 16:48:29,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 16:48:29,458] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:12:08,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:12:08,929] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:34:20,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:34:20,469] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 17:51:14,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 17:51:14,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 18:17:39,630] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 18:17:39,869] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 18:47:32,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 18:47:32,626] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:10:17,896] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:10:18,190] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:25:15,057] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:25:15,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:35:19,137] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:35:19,346] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 19:47:59,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 19:47:59,882] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:14:07,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:14:07,819] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:34:06,127] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:34:06,600] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 20:51:01,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 20:51:01,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:11:45,482] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:11:45,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:29:54,304] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:29:54,513] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:41:54,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:41:55,267] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 21:50:52,524] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 21:50:52,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:12:14,920] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:12:15,145] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:34:11,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:34:12,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 22:50:37,208] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 22:50:37,476] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:12:18,164] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:12:18,496] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:29:59,761] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:30:00,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:42:01,442] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:42:01,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-01 23:49:54,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-01 23:49:54,637] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 01:02:34,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 01:02:34,744] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 02:56:04,877] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 02:56:05,046] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 03:47:39,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 03:47:40,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 04:23:18,582] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 04:23:18,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 04:49:02,829] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 04:49:03,237] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:15:16,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:15:17,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:40:25,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:40:25,958] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 05:52:19,286] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 05:52:19,613] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 06:19:44,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 06:19:44,623] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 06:50:00,814] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 06:50:01,200] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:13:28,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:13:29,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:31:20,809] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:31:21,213] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 07:48:32,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 07:48:32,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 08:17:58,229] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 08:17:58,577] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 08:47:52,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 08:47:52,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:15:30,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:15:31,124] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:42:32,256] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:42:32,635] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 09:52:28,257] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 09:52:28,593] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:14:16,926] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:14:17,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:40:11,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:40:11,550] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 10:53:18,437] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 10:53:18,831] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:11:46,266] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:11:46,642] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:28:10,139] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:28:10,446] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:38:57,493] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:38:57,863] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 11:48:02,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 11:48:02,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 12:25:01,819] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 12:25:02,061] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:06:45,198] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:06:45,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:43:11,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:43:11,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 13:54:00,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 13:54:00,723] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:13:01,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:13:02,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:35:26,916] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:35:27,134] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 14:52:12,942] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 14:52:13,188] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:13:44,945] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:13:45,252] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:34:34,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:34:35,167] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 15:51:35,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 15:51:35,411] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 16:15:36,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 16:15:37,014] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 16:47:49,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 16:47:49,475] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 17:12:39,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 17:12:39,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 17:33:21,631] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 17:33:21,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 17:49:29,703] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 17:49:30,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 18:18:13,071] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 18:18:13,374] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 18:48:22,728] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 18:48:23,053] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 19:10:02,052] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 19:10:02,337] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 19:25:20,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 19:25:20,725] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 19:34:37,064] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 19:34:37,364] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 19:47:44,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 19:47:44,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 20:13:09,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 20:13:09,717] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 20:32:05,449] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 20:32:05,774] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 20:50:08,550] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 20:50:08,929] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 21:11:52,222] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 21:11:52,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 21:30:00,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 21:30:00,694] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 21:41:46,564] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 21:41:46,935] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 21:49:04,823] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 21:49:05,188] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 22:12:20,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 22:12:21,303] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 22:33:59,885] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 22:34:00,037] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 22:50:18,833] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 22:50:19,134] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 23:12:32,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 23:12:33,118] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 23:31:03,950] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 23:31:04,242] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-02 23:49:10,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-02 23:49:10,645] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 01:02:16,525] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 01:02:16,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 02:57:58,724] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 02:57:58,969] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 03:52:27,934] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 03:52:28,250] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 04:25:23,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 04:25:23,918] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 04:52:39,079] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 04:52:39,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 05:17:08,695] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 05:17:09,124] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 05:44:43,476] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 05:44:43,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 05:54:35,901] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 05:54:36,293] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 06:19:47,410] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 06:19:47,751] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 06:50:48,948] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 06:50:49,341] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 07:13:52,199] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 07:13:52,636] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 07:31:40,645] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 07:31:40,912] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 07:48:37,771] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 07:48:38,111] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 08:17:36,380] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 08:17:36,786] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 08:46:27,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 08:46:28,094] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 09:14:35,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 09:14:36,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 09:35:37,914] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 09:35:38,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 09:51:47,429] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 09:51:47,751] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 10:14:21,187] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 10:14:21,580] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 10:39:28,174] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 10:39:28,380] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 10:53:06,655] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 10:53:06,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 11:11:42,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 11:11:43,233] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 11:28:16,860] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 11:28:17,164] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 11:39:26,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 11:39:27,135] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 11:47:39,938] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 11:47:40,182] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 12:25:33,612] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 12:25:33,998] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 13:04:48,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 13:04:48,901] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 13:42:02,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 13:42:02,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 13:53:57,265] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 13:53:57,574] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 14:12:56,662] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 14:12:57,054] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 14:35:07,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 14:35:08,361] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 14:51:57,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 14:51:58,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 15:13:49,656] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 15:13:49,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 15:34:04,537] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 15:34:04,888] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 15:51:26,921] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 15:51:27,304] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 16:15:47,780] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 16:15:48,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 16:47:19,657] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 16:47:19,882] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 17:13:40,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 17:13:40,790] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 17:34:07,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 17:34:07,403] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 17:49:52,231] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 17:49:52,551] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 18:17:38,290] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 18:17:38,664] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 18:47:42,996] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 18:47:43,370] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 19:10:03,103] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 19:10:03,422] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 19:24:57,056] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 19:24:57,396] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 19:34:34,094] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 19:34:34,367] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 19:47:49,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 19:47:49,646] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 20:12:54,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 20:12:54,442] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 20:33:03,069] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 20:33:03,436] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 20:51:43,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 20:51:44,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 21:11:39,755] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 21:11:40,013] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 21:29:38,103] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 21:29:38,475] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 21:41:23,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 21:41:23,537] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 21:48:38,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 21:48:38,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 22:12:15,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 22:12:15,670] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 22:33:35,576] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 22:33:35,958] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 22:50:19,345] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 22:50:19,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 23:12:27,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 23:12:27,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 23:29:39,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 23:29:39,539] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 23:42:06,641] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 23:42:07,011] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-03 23:50:09,376] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-03 23:50:09,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 01:02:01,854] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 01:02:02,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 02:56:04,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 02:56:04,692] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 03:46:36,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 03:46:37,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 04:23:34,581] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 04:23:34,749] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 04:50:17,230] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 04:50:17,602] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 05:15:37,004] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 05:15:37,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 05:44:09,590] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 05:44:09,962] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 05:54:15,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 05:54:15,905] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 06:19:18,581] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 06:19:18,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 06:51:02,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 06:51:03,301] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 07:13:50,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 07:13:50,491] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 07:33:15,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 07:33:15,911] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 07:49:41,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 07:49:41,496] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 08:17:39,459] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 08:17:39,886] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 08:46:35,698] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 08:46:36,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 09:14:07,223] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 09:14:07,519] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 09:34:21,895] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 09:34:22,302] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 09:50:22,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 09:50:22,346] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 10:13:49,399] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 10:13:49,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 10:38:13,019] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 10:38:13,392] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 10:52:16,570] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 10:52:17,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 11:12:03,231] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 11:12:03,507] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 11:27:52,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 11:27:52,871] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 11:38:32,066] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 11:38:32,440] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 11:47:46,864] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 11:47:47,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 12:24:56,116] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 12:24:56,506] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 13:04:53,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 13:04:53,856] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 13:41:22,230] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 13:41:22,638] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 13:52:17,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 13:52:37,019] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 14:12:43,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 14:12:44,350] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 14:34:03,574] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 14:34:03,943] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 14:52:18,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 14:52:18,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 15:12:33,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 15:12:33,510] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-07-04 15:32:17,517] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-07-04 15:32:17,973] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
