[2025-03-01 00:57:57,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 00:57:58,194] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 02:23:01,249] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 02:23:01,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 03:08:56,204] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 03:08:56,605] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 03:39:36,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 03:39:36,798] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 03:50:53,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 03:50:54,222] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 04:13:35,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 04:13:35,911] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 04:32:08,305] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 04:32:08,724] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 04:47:35,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 04:47:36,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 05:10:52,439] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 05:10:52,761] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 05:28:46,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 05:28:46,835] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 05:38:27,673] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 05:38:28,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 05:47:40,420] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 05:47:40,813] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 06:15:06,175] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 06:15:06,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 06:37:11,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 06:37:11,745] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 06:49:15,075] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 06:49:15,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 07:10:12,424] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 07:10:12,778] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 07:24:22,156] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 07:24:22,493] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 07:33:35,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 07:33:36,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 07:48:01,673] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 07:48:02,200] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 08:13:45,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 08:13:45,564] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 08:32:09,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 08:32:10,106] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 08:48:11,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 08:48:11,985] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 09:11:03,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 09:11:03,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 09:26:06,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 09:26:06,422] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 09:35:00,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 09:35:00,599] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 09:47:49,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 09:47:50,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 10:10:53,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 10:10:53,523] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 10:30:29,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 10:30:29,670] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 10:40:24,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 10:40:24,929] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 10:47:40,680] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 10:47:41,041] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 11:08:37,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 11:08:37,341] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 11:21:47,163] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 11:21:47,520] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 11:34:41,060] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 11:34:41,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 11:47:44,709] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 11:47:45,079] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 12:19:06,025] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 12:19:06,332] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 12:53:11,011] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 12:53:11,299] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 13:15:04,410] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 13:15:04,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 13:29:30,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 13:29:31,023] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 13:37:22,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 13:37:23,150] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 13:47:49,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 13:47:49,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 14:09:33,888] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 14:09:34,231] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 14:28:31,384] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 14:28:31,718] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 14:37:57,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 14:37:57,788] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 14:47:43,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 14:47:43,518] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 15:10:11,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 15:10:11,471] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 15:28:01,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 15:28:01,494] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 15:37:19,571] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 15:37:19,879] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 15:47:50,016] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 15:47:50,372] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 16:12:03,228] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 16:12:03,568] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 16:31:51,558] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 16:31:51,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 16:47:34,174] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 16:47:34,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 17:09:15,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 17:09:15,480] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 17:26:01,088] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 17:26:01,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 17:34:01,685] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 17:34:02,043] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 17:47:53,933] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 17:47:54,271] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 18:13:52,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 18:13:52,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 18:33:59,176] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 18:33:59,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 18:47:52,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 18:47:52,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 19:08:19,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 19:08:19,929] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 19:20:49,436] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 19:20:49,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 19:33:39,151] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 19:33:39,509] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 19:47:45,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 19:47:45,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 20:11:15,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 20:11:16,028] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 20:26:58,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 20:26:59,355] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 20:35:57,508] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 20:35:57,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 20:47:45,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 20:47:46,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 21:09:40,854] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 21:09:41,205] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 21:26:05,588] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 21:26:05,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 21:33:52,776] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 21:33:53,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 21:47:46,894] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 21:47:47,230] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 22:09:53,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 22:09:53,597] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 22:29:04,080] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 22:29:04,435] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 22:38:50,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 22:38:50,876] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 22:47:55,831] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 22:47:56,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 23:11:31,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 23:11:31,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 23:26:30,199] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 23:26:30,559] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 23:34:58,463] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 23:34:58,833] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-01 23:47:46,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-01 23:47:46,667] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 00:57:00,527] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 00:57:00,706] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 02:21:22,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 02:21:23,336] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 03:06:41,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 03:06:42,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 03:36:35,987] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 03:36:36,342] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 03:49:24,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 03:49:25,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 04:13:07,773] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 04:13:08,207] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 04:31:18,760] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 04:31:18,968] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 04:47:47,466] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 04:47:47,712] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 05:11:29,252] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 05:11:29,614] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 05:30:34,294] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 05:30:34,651] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 05:47:32,812] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 05:47:33,262] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 06:15:12,487] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 06:15:12,723] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 06:36:33,999] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 06:36:34,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 06:48:49,376] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 06:48:49,701] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 07:10:05,289] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 07:10:05,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 07:23:42,504] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 07:23:42,861] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 07:33:41,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 07:33:41,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 07:47:52,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 07:47:52,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 08:13:10,486] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 08:13:10,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 08:31:09,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 08:31:09,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 08:47:39,817] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 08:47:40,157] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 09:10:28,803] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 09:10:29,055] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 09:27:05,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 09:27:06,056] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 09:35:41,570] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 09:35:41,953] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 09:47:48,443] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 09:47:48,794] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 10:11:16,732] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 10:11:17,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 10:30:44,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 10:30:44,923] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 10:47:53,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 10:47:53,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 11:09:21,500] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 11:09:21,858] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 11:22:14,709] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 11:22:15,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 11:33:30,446] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 11:33:30,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 11:47:35,503] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 11:47:35,865] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 12:18:34,901] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 12:18:35,300] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 12:52:23,405] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 12:52:23,724] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 13:14:42,509] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 13:14:42,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 13:29:18,843] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 13:29:19,214] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 13:37:03,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 13:37:04,076] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 13:47:38,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 13:47:38,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 14:09:37,395] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 14:09:37,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 14:27:55,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 14:27:55,423] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 14:37:34,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 14:37:34,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 14:47:42,986] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 14:47:43,344] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 15:10:05,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 15:10:05,940] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 15:26:43,581] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 15:26:43,941] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 15:36:01,749] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 15:36:02,154] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 15:47:42,200] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 15:47:42,549] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 16:12:49,427] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 16:12:49,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 16:32:40,953] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 16:32:41,308] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 16:47:38,370] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 16:47:38,708] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 17:09:09,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 17:09:09,341] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 17:26:01,281] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 17:26:01,639] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 17:35:24,821] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 17:35:25,248] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 17:47:47,088] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 17:47:47,366] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 18:14:11,910] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 18:14:12,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 18:36:30,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 18:36:30,888] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 18:49:13,263] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 18:49:13,553] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 19:08:38,073] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 19:08:38,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 19:22:02,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 19:22:02,943] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 19:33:15,058] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 19:33:15,253] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 19:47:48,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 19:47:48,264] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 20:11:19,312] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 20:11:19,641] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 20:27:09,845] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 20:27:10,098] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 20:35:47,085] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 20:35:47,396] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 20:47:37,851] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 20:47:38,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 21:10:06,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 21:10:06,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 21:24:42,506] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 21:24:42,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 21:33:12,065] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 21:33:12,396] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 21:47:44,465] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 21:47:44,663] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 22:09:46,824] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 22:09:47,128] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 22:29:31,537] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 22:29:31,802] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 22:39:22,417] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 22:39:22,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 22:47:34,946] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 22:47:35,299] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 23:10:19,096] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 23:10:19,402] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 23:25:00,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 23:25:00,960] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 23:33:44,660] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 23:33:44,942] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-02 23:47:59,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-02 23:47:59,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 00:55:42,366] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 00:55:42,715] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 02:18:22,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 02:18:22,707] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 03:06:14,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 03:06:14,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 03:37:35,533] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 03:37:35,899] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 03:51:54,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 03:51:54,783] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 04:15:01,057] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 04:15:01,252] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 04:34:56,388] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 04:34:56,634] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 04:49:19,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 04:49:20,171] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 05:12:15,469] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 05:12:15,821] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 05:31:08,387] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 05:31:08,746] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 05:47:30,888] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 05:47:31,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 06:17:14,783] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 06:17:15,085] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 06:44:25,949] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 06:44:26,283] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 06:53:04,647] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 06:53:04,901] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 07:12:24,755] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 07:12:25,009] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 07:27:27,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 07:27:27,499] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 07:35:53,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 07:35:54,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 07:47:53,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 07:47:53,403] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 08:16:18,573] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 08:16:18,773] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 08:41:03,326] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 08:41:03,542] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 08:50:33,687] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 08:50:33,980] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-03-03 09:13:42,227] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-03-03 09:13:42,429] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
