[2025-05-01 01:04:15,995] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 01:04:16,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 02:55:06,958] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 02:55:07,315] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 03:41:32,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 03:41:33,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:02:19,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:02:20,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:36:46,166] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:36:46,482] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 04:52:08,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 04:52:09,023] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:13:10,431] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:13:10,704] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:33:13,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:33:13,470] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 05:47:59,893] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 05:48:00,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:18:21,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:18:21,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 06:46:51,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 06:46:51,770] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:12:45,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:12:46,052] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:28:44,123] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:28:44,460] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:38:11,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:38:11,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 07:47:46,152] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 07:47:46,450] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:16:30,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:16:30,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:43:10,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:43:11,133] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 08:54:27,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 08:54:27,274] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:13:09,063] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:13:09,422] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:31:18,014] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:31:18,373] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 09:47:39,100] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 09:47:39,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:12:46,097] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:12:46,297] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:35:52,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:35:52,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 10:50:12,978] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 10:50:13,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:10:33,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:10:33,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:24:54,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:24:54,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:33:51,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:33:52,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 11:47:56,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 11:47:57,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 12:22:25,617] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 12:22:25,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:00:41,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:00:41,719] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:35:43,744] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:35:43,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 13:48:42,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 13:48:43,106] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:11:37,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:11:37,890] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:31:38,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:31:38,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 14:48:02,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 14:48:02,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:12:01,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:12:02,075] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:30:47,624] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:30:47,965] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 15:48:24,738] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 15:48:25,101] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:15:10,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:15:11,220] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:39:54,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:39:55,243] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 16:53:27,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 16:53:28,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:11:00,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:11:00,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:30:07,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:30:07,683] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:41:22,634] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:41:23,051] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 17:48:33,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 17:48:33,650] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 18:17:00,722] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 18:17:01,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 18:45:51,388] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 18:45:51,737] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:09:31,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:09:32,143] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:23:30,410] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:23:30,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:33:58,683] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:33:59,072] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 19:47:41,631] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 19:47:42,025] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:12:39,699] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:12:40,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:30:33,511] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:30:33,850] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 20:47:42,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 20:47:42,432] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:11:47,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:11:48,221] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:27:07,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:27:07,574] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:36:04,911] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:36:05,313] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 21:47:43,961] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 21:47:44,219] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:11:41,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:11:42,036] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:32:47,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:32:47,634] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 22:48:00,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 22:48:00,448] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:11:54,391] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:11:54,754] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:28:19,741] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:28:20,083] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:38:43,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:38:44,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-01 23:47:44,516] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-01 23:47:44,918] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 00:58:56,414] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 00:58:56,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 02:38:12,216] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 02:38:12,456] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 03:30:10,825] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 03:30:11,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 03:53:29,753] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 03:53:30,087] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:14:56,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:14:57,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:36:59,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:36:59,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 04:52:20,802] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 04:52:21,137] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:12:56,519] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:12:56,931] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:33:15,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:33:15,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 05:47:55,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 05:47:55,390] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 06:17:30,454] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 06:17:30,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 06:46:21,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 06:46:22,007] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:12:25,813] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:12:26,177] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:28:49,335] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:28:49,693] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:38:28,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:38:28,601] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 07:47:38,361] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 07:47:38,699] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 08:16:10,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 08:16:10,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2025-05-02 08:43:43,140] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2025-05-02 08:43:43,518] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
